// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.ovhcloud.pulumi.ovh.outputs;

import com.ovhcloud.pulumi.ovh.outputs.GetCloudNetworkPrivateVrackSubnetCurrentStateAllocationPool;
import com.ovhcloud.pulumi.ovh.outputs.GetCloudNetworkPrivateVrackSubnetCurrentStateHostRoute;
import com.ovhcloud.pulumi.ovh.outputs.GetCloudNetworkPrivateVrackSubnetCurrentStateLocation;
import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.lang.String;
import java.util.List;
import java.util.Objects;

@CustomType
public final class GetCloudNetworkPrivateVrackSubnetCurrentState {
    /**
     * @return IP address allocation pools:
     * 
     */
    private List<GetCloudNetworkPrivateVrackSubnetCurrentStateAllocationPool> allocationPools;
    /**
     * @return CIDR address range.
     * 
     */
    private String cidr;
    /**
     * @return Subnet description.
     * 
     */
    private String description;
    /**
     * @return Whether DHCP is enabled.
     * 
     */
    private Boolean dhcpEnabled;
    /**
     * @return Configured DNS nameservers.
     * 
     */
    private List<String> dnsNameservers;
    /**
     * @return Default gateway IP address.
     * 
     */
    private String gatewayIp;
    /**
     * @return Static host routes:
     * 
     */
    private List<GetCloudNetworkPrivateVrackSubnetCurrentStateHostRoute> hostRoutes;
    /**
     * @return Location details:
     * 
     */
    private GetCloudNetworkPrivateVrackSubnetCurrentStateLocation location;
    /**
     * @return Subnet name.
     * 
     */
    private String name;

    private GetCloudNetworkPrivateVrackSubnetCurrentState() {}
    /**
     * @return IP address allocation pools:
     * 
     */
    public List<GetCloudNetworkPrivateVrackSubnetCurrentStateAllocationPool> allocationPools() {
        return this.allocationPools;
    }
    /**
     * @return CIDR address range.
     * 
     */
    public String cidr() {
        return this.cidr;
    }
    /**
     * @return Subnet description.
     * 
     */
    public String description() {
        return this.description;
    }
    /**
     * @return Whether DHCP is enabled.
     * 
     */
    public Boolean dhcpEnabled() {
        return this.dhcpEnabled;
    }
    /**
     * @return Configured DNS nameservers.
     * 
     */
    public List<String> dnsNameservers() {
        return this.dnsNameservers;
    }
    /**
     * @return Default gateway IP address.
     * 
     */
    public String gatewayIp() {
        return this.gatewayIp;
    }
    /**
     * @return Static host routes:
     * 
     */
    public List<GetCloudNetworkPrivateVrackSubnetCurrentStateHostRoute> hostRoutes() {
        return this.hostRoutes;
    }
    /**
     * @return Location details:
     * 
     */
    public GetCloudNetworkPrivateVrackSubnetCurrentStateLocation location() {
        return this.location;
    }
    /**
     * @return Subnet name.
     * 
     */
    public String name() {
        return this.name;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetCloudNetworkPrivateVrackSubnetCurrentState defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private List<GetCloudNetworkPrivateVrackSubnetCurrentStateAllocationPool> allocationPools;
        private String cidr;
        private String description;
        private Boolean dhcpEnabled;
        private List<String> dnsNameservers;
        private String gatewayIp;
        private List<GetCloudNetworkPrivateVrackSubnetCurrentStateHostRoute> hostRoutes;
        private GetCloudNetworkPrivateVrackSubnetCurrentStateLocation location;
        private String name;
        public Builder() {}
        public Builder(GetCloudNetworkPrivateVrackSubnetCurrentState defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.allocationPools = defaults.allocationPools;
    	      this.cidr = defaults.cidr;
    	      this.description = defaults.description;
    	      this.dhcpEnabled = defaults.dhcpEnabled;
    	      this.dnsNameservers = defaults.dnsNameservers;
    	      this.gatewayIp = defaults.gatewayIp;
    	      this.hostRoutes = defaults.hostRoutes;
    	      this.location = defaults.location;
    	      this.name = defaults.name;
        }

        @CustomType.Setter
        public Builder allocationPools(List<GetCloudNetworkPrivateVrackSubnetCurrentStateAllocationPool> allocationPools) {
            if (allocationPools == null) {
              throw new MissingRequiredPropertyException("GetCloudNetworkPrivateVrackSubnetCurrentState", "allocationPools");
            }
            this.allocationPools = allocationPools;
            return this;
        }
        public Builder allocationPools(GetCloudNetworkPrivateVrackSubnetCurrentStateAllocationPool... allocationPools) {
            return allocationPools(List.of(allocationPools));
        }
        @CustomType.Setter
        public Builder cidr(String cidr) {
            if (cidr == null) {
              throw new MissingRequiredPropertyException("GetCloudNetworkPrivateVrackSubnetCurrentState", "cidr");
            }
            this.cidr = cidr;
            return this;
        }
        @CustomType.Setter
        public Builder description(String description) {
            if (description == null) {
              throw new MissingRequiredPropertyException("GetCloudNetworkPrivateVrackSubnetCurrentState", "description");
            }
            this.description = description;
            return this;
        }
        @CustomType.Setter
        public Builder dhcpEnabled(Boolean dhcpEnabled) {
            if (dhcpEnabled == null) {
              throw new MissingRequiredPropertyException("GetCloudNetworkPrivateVrackSubnetCurrentState", "dhcpEnabled");
            }
            this.dhcpEnabled = dhcpEnabled;
            return this;
        }
        @CustomType.Setter
        public Builder dnsNameservers(List<String> dnsNameservers) {
            if (dnsNameservers == null) {
              throw new MissingRequiredPropertyException("GetCloudNetworkPrivateVrackSubnetCurrentState", "dnsNameservers");
            }
            this.dnsNameservers = dnsNameservers;
            return this;
        }
        public Builder dnsNameservers(String... dnsNameservers) {
            return dnsNameservers(List.of(dnsNameservers));
        }
        @CustomType.Setter
        public Builder gatewayIp(String gatewayIp) {
            if (gatewayIp == null) {
              throw new MissingRequiredPropertyException("GetCloudNetworkPrivateVrackSubnetCurrentState", "gatewayIp");
            }
            this.gatewayIp = gatewayIp;
            return this;
        }
        @CustomType.Setter
        public Builder hostRoutes(List<GetCloudNetworkPrivateVrackSubnetCurrentStateHostRoute> hostRoutes) {
            if (hostRoutes == null) {
              throw new MissingRequiredPropertyException("GetCloudNetworkPrivateVrackSubnetCurrentState", "hostRoutes");
            }
            this.hostRoutes = hostRoutes;
            return this;
        }
        public Builder hostRoutes(GetCloudNetworkPrivateVrackSubnetCurrentStateHostRoute... hostRoutes) {
            return hostRoutes(List.of(hostRoutes));
        }
        @CustomType.Setter
        public Builder location(GetCloudNetworkPrivateVrackSubnetCurrentStateLocation location) {
            if (location == null) {
              throw new MissingRequiredPropertyException("GetCloudNetworkPrivateVrackSubnetCurrentState", "location");
            }
            this.location = location;
            return this;
        }
        @CustomType.Setter
        public Builder name(String name) {
            if (name == null) {
              throw new MissingRequiredPropertyException("GetCloudNetworkPrivateVrackSubnetCurrentState", "name");
            }
            this.name = name;
            return this;
        }
        public GetCloudNetworkPrivateVrackSubnetCurrentState build() {
            final var _resultValue = new GetCloudNetworkPrivateVrackSubnetCurrentState();
            _resultValue.allocationPools = allocationPools;
            _resultValue.cidr = cidr;
            _resultValue.description = description;
            _resultValue.dhcpEnabled = dhcpEnabled;
            _resultValue.dnsNameservers = dnsNameservers;
            _resultValue.gatewayIp = gatewayIp;
            _resultValue.hostRoutes = hostRoutes;
            _resultValue.location = location;
            _resultValue.name = name;
            return _resultValue;
        }
    }
}
