// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.ovhcloud.pulumi.ovh.outputs;

import com.ovhcloud.pulumi.ovh.outputs.GetCloudQuotaCurrentStateRegionVolumeBackupSizeTotal;
import com.ovhcloud.pulumi.ovh.outputs.GetCloudQuotaCurrentStateRegionVolumeBackups;
import com.ovhcloud.pulumi.ovh.outputs.GetCloudQuotaCurrentStateRegionVolumePerVolumeSize;
import com.ovhcloud.pulumi.ovh.outputs.GetCloudQuotaCurrentStateRegionVolumeSizeTotal;
import com.ovhcloud.pulumi.ovh.outputs.GetCloudQuotaCurrentStateRegionVolumeSnapshots;
import com.ovhcloud.pulumi.ovh.outputs.GetCloudQuotaCurrentStateRegionVolumeVolumes;
import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.util.Objects;

@CustomType
public final class GetCloudQuotaCurrentStateRegionVolume {
    private GetCloudQuotaCurrentStateRegionVolumeBackupSizeTotal backupSizeTotal;
    private GetCloudQuotaCurrentStateRegionVolumeBackups backups;
    private GetCloudQuotaCurrentStateRegionVolumePerVolumeSize perVolumeSize;
    private GetCloudQuotaCurrentStateRegionVolumeSizeTotal sizeTotal;
    private GetCloudQuotaCurrentStateRegionVolumeSnapshots snapshots;
    private GetCloudQuotaCurrentStateRegionVolumeVolumes volumes;

    private GetCloudQuotaCurrentStateRegionVolume() {}
    public GetCloudQuotaCurrentStateRegionVolumeBackupSizeTotal backupSizeTotal() {
        return this.backupSizeTotal;
    }
    public GetCloudQuotaCurrentStateRegionVolumeBackups backups() {
        return this.backups;
    }
    public GetCloudQuotaCurrentStateRegionVolumePerVolumeSize perVolumeSize() {
        return this.perVolumeSize;
    }
    public GetCloudQuotaCurrentStateRegionVolumeSizeTotal sizeTotal() {
        return this.sizeTotal;
    }
    public GetCloudQuotaCurrentStateRegionVolumeSnapshots snapshots() {
        return this.snapshots;
    }
    public GetCloudQuotaCurrentStateRegionVolumeVolumes volumes() {
        return this.volumes;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetCloudQuotaCurrentStateRegionVolume defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private GetCloudQuotaCurrentStateRegionVolumeBackupSizeTotal backupSizeTotal;
        private GetCloudQuotaCurrentStateRegionVolumeBackups backups;
        private GetCloudQuotaCurrentStateRegionVolumePerVolumeSize perVolumeSize;
        private GetCloudQuotaCurrentStateRegionVolumeSizeTotal sizeTotal;
        private GetCloudQuotaCurrentStateRegionVolumeSnapshots snapshots;
        private GetCloudQuotaCurrentStateRegionVolumeVolumes volumes;
        public Builder() {}
        public Builder(GetCloudQuotaCurrentStateRegionVolume defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.backupSizeTotal = defaults.backupSizeTotal;
    	      this.backups = defaults.backups;
    	      this.perVolumeSize = defaults.perVolumeSize;
    	      this.sizeTotal = defaults.sizeTotal;
    	      this.snapshots = defaults.snapshots;
    	      this.volumes = defaults.volumes;
        }

        @CustomType.Setter
        public Builder backupSizeTotal(GetCloudQuotaCurrentStateRegionVolumeBackupSizeTotal backupSizeTotal) {
            if (backupSizeTotal == null) {
              throw new MissingRequiredPropertyException("GetCloudQuotaCurrentStateRegionVolume", "backupSizeTotal");
            }
            this.backupSizeTotal = backupSizeTotal;
            return this;
        }
        @CustomType.Setter
        public Builder backups(GetCloudQuotaCurrentStateRegionVolumeBackups backups) {
            if (backups == null) {
              throw new MissingRequiredPropertyException("GetCloudQuotaCurrentStateRegionVolume", "backups");
            }
            this.backups = backups;
            return this;
        }
        @CustomType.Setter
        public Builder perVolumeSize(GetCloudQuotaCurrentStateRegionVolumePerVolumeSize perVolumeSize) {
            if (perVolumeSize == null) {
              throw new MissingRequiredPropertyException("GetCloudQuotaCurrentStateRegionVolume", "perVolumeSize");
            }
            this.perVolumeSize = perVolumeSize;
            return this;
        }
        @CustomType.Setter
        public Builder sizeTotal(GetCloudQuotaCurrentStateRegionVolumeSizeTotal sizeTotal) {
            if (sizeTotal == null) {
              throw new MissingRequiredPropertyException("GetCloudQuotaCurrentStateRegionVolume", "sizeTotal");
            }
            this.sizeTotal = sizeTotal;
            return this;
        }
        @CustomType.Setter
        public Builder snapshots(GetCloudQuotaCurrentStateRegionVolumeSnapshots snapshots) {
            if (snapshots == null) {
              throw new MissingRequiredPropertyException("GetCloudQuotaCurrentStateRegionVolume", "snapshots");
            }
            this.snapshots = snapshots;
            return this;
        }
        @CustomType.Setter
        public Builder volumes(GetCloudQuotaCurrentStateRegionVolumeVolumes volumes) {
            if (volumes == null) {
              throw new MissingRequiredPropertyException("GetCloudQuotaCurrentStateRegionVolume", "volumes");
            }
            this.volumes = volumes;
            return this;
        }
        public GetCloudQuotaCurrentStateRegionVolume build() {
            final var _resultValue = new GetCloudQuotaCurrentStateRegionVolume();
            _resultValue.backupSizeTotal = backupSizeTotal;
            _resultValue.backups = backups;
            _resultValue.perVolumeSize = perVolumeSize;
            _resultValue.sizeTotal = sizeTotal;
            _resultValue.snapshots = snapshots;
            _resultValue.volumes = volumes;
            return _resultValue;
        }
    }
}
