// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.ovhcloud.ovh.CloudProject.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class GatewayInterface {
    /**
     * @return ID of the interface.
     * 
     */
    private @Nullable String id;
    /**
     * @return IP of the interface.
     * 
     */
    private @Nullable String ip;
    /**
     * @return ID of the private network.
     * 
     */
    private @Nullable String networkId;
    /**
     * @return ID of the subnet.
     * 
     */
    private @Nullable String subnetId;

    private GatewayInterface() {}
    /**
     * @return ID of the interface.
     * 
     */
    public Optional<String> id() {
        return Optional.ofNullable(this.id);
    }
    /**
     * @return IP of the interface.
     * 
     */
    public Optional<String> ip() {
        return Optional.ofNullable(this.ip);
    }
    /**
     * @return ID of the private network.
     * 
     */
    public Optional<String> networkId() {
        return Optional.ofNullable(this.networkId);
    }
    /**
     * @return ID of the subnet.
     * 
     */
    public Optional<String> subnetId() {
        return Optional.ofNullable(this.subnetId);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GatewayInterface defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable String id;
        private @Nullable String ip;
        private @Nullable String networkId;
        private @Nullable String subnetId;
        public Builder() {}
        public Builder(GatewayInterface defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.id = defaults.id;
    	      this.ip = defaults.ip;
    	      this.networkId = defaults.networkId;
    	      this.subnetId = defaults.subnetId;
        }

        @CustomType.Setter
        public Builder id(@Nullable String id) {

            this.id = id;
            return this;
        }
        @CustomType.Setter
        public Builder ip(@Nullable String ip) {

            this.ip = ip;
            return this;
        }
        @CustomType.Setter
        public Builder networkId(@Nullable String networkId) {

            this.networkId = networkId;
            return this;
        }
        @CustomType.Setter
        public Builder subnetId(@Nullable String subnetId) {

            this.subnetId = subnetId;
            return this;
        }
        public GatewayInterface build() {
            final var _resultValue = new GatewayInterface();
            _resultValue.id = id;
            _resultValue.ip = ip;
            _resultValue.networkId = networkId;
            _resultValue.subnetId = subnetId;
            return _resultValue;
        }
    }
}
