// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.ovhcloud.ovh.CloudProject.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class GetUserS3PolicyResult {
    /**
     * @return The provider-assigned unique ID for this managed resource.
     * 
     */
    private String id;
    /**
     * @return (Required) The policy document. This is a JSON formatted string.
     * 
     */
    private String policy;
    private String serviceName;
    private String userId;

    private GetUserS3PolicyResult() {}
    /**
     * @return The provider-assigned unique ID for this managed resource.
     * 
     */
    public String id() {
        return this.id;
    }
    /**
     * @return (Required) The policy document. This is a JSON formatted string.
     * 
     */
    public String policy() {
        return this.policy;
    }
    public String serviceName() {
        return this.serviceName;
    }
    public String userId() {
        return this.userId;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetUserS3PolicyResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String id;
        private String policy;
        private String serviceName;
        private String userId;
        public Builder() {}
        public Builder(GetUserS3PolicyResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.id = defaults.id;
    	      this.policy = defaults.policy;
    	      this.serviceName = defaults.serviceName;
    	      this.userId = defaults.userId;
        }

        @CustomType.Setter
        public Builder id(String id) {
            if (id == null) {
              throw new MissingRequiredPropertyException("GetUserS3PolicyResult", "id");
            }
            this.id = id;
            return this;
        }
        @CustomType.Setter
        public Builder policy(String policy) {
            if (policy == null) {
              throw new MissingRequiredPropertyException("GetUserS3PolicyResult", "policy");
            }
            this.policy = policy;
            return this;
        }
        @CustomType.Setter
        public Builder serviceName(String serviceName) {
            if (serviceName == null) {
              throw new MissingRequiredPropertyException("GetUserS3PolicyResult", "serviceName");
            }
            this.serviceName = serviceName;
            return this;
        }
        @CustomType.Setter
        public Builder userId(String userId) {
            if (userId == null) {
              throw new MissingRequiredPropertyException("GetUserS3PolicyResult", "userId");
            }
            this.userId = userId;
            return this;
        }
        public GetUserS3PolicyResult build() {
            final var _resultValue = new GetUserS3PolicyResult();
            _resultValue.id = id;
            _resultValue.policy = policy;
            _resultValue.serviceName = serviceName;
            _resultValue.userId = userId;
            return _resultValue;
        }
    }
}
