// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.ovhcloud.pulumi.ovh.Domain.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class ZonePlanConfigurationArgs extends com.pulumi.resources.ResourceArgs {

    public static final ZonePlanConfigurationArgs Empty = new ZonePlanConfigurationArgs();

    /**
     * Identifier of the resource : `zone` or `template`
     * 
     */
    @Import(name="label", required=true)
    private Output<String> label;

    /**
     * @return Identifier of the resource : `zone` or `template`
     * 
     */
    public Output<String> label() {
        return this.label;
    }

    /**
     * For `zone`, the value is the zone name `myzone.example.com`. For `template`, the value can be `basic`, `minimized` or `redirect` which is the same as `minimized` with additional entries for a redirect configuration.
     * 
     */
    @Import(name="value", required=true)
    private Output<String> value;

    /**
     * @return For `zone`, the value is the zone name `myzone.example.com`. For `template`, the value can be `basic`, `minimized` or `redirect` which is the same as `minimized` with additional entries for a redirect configuration.
     * 
     */
    public Output<String> value() {
        return this.value;
    }

    private ZonePlanConfigurationArgs() {}

    private ZonePlanConfigurationArgs(ZonePlanConfigurationArgs $) {
        this.label = $.label;
        this.value = $.value;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ZonePlanConfigurationArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ZonePlanConfigurationArgs $;

        public Builder() {
            $ = new ZonePlanConfigurationArgs();
        }

        public Builder(ZonePlanConfigurationArgs defaults) {
            $ = new ZonePlanConfigurationArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param label Identifier of the resource : `zone` or `template`
         * 
         * @return builder
         * 
         */
        public Builder label(Output<String> label) {
            $.label = label;
            return this;
        }

        /**
         * @param label Identifier of the resource : `zone` or `template`
         * 
         * @return builder
         * 
         */
        public Builder label(String label) {
            return label(Output.of(label));
        }

        /**
         * @param value For `zone`, the value is the zone name `myzone.example.com`. For `template`, the value can be `basic`, `minimized` or `redirect` which is the same as `minimized` with additional entries for a redirect configuration.
         * 
         * @return builder
         * 
         */
        public Builder value(Output<String> value) {
            $.value = value;
            return this;
        }

        /**
         * @param value For `zone`, the value is the zone name `myzone.example.com`. For `template`, the value can be `basic`, `minimized` or `redirect` which is the same as `minimized` with additional entries for a redirect configuration.
         * 
         * @return builder
         * 
         */
        public Builder value(String value) {
            return value(Output.of(value));
        }

        public ZonePlanConfigurationArgs build() {
            if ($.label == null) {
                throw new MissingRequiredPropertyException("ZonePlanConfigurationArgs", "label");
            }
            if ($.value == null) {
                throw new MissingRequiredPropertyException("ZonePlanConfigurationArgs", "value");
            }
            return $;
        }
    }

}
