// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.ovhcloud.pulumi.ovh.inputs;

import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class GetCloudStorageBlockVolumesPlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetCloudStorageBlockVolumesPlainArgs Empty = new GetCloudStorageBlockVolumesPlainArgs();

    /**
     * The region where the volumes reside.
     * 
     */
    @Import(name="region", required=true)
    private String region;

    /**
     * @return The region where the volumes reside.
     * 
     */
    public String region() {
        return this.region;
    }

    /**
     * The id of the public cloud project.
     * 
     */
    @Import(name="serviceName", required=true)
    private String serviceName;

    /**
     * @return The id of the public cloud project.
     * 
     */
    public String serviceName() {
        return this.serviceName;
    }

    private GetCloudStorageBlockVolumesPlainArgs() {}

    private GetCloudStorageBlockVolumesPlainArgs(GetCloudStorageBlockVolumesPlainArgs $) {
        this.region = $.region;
        this.serviceName = $.serviceName;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetCloudStorageBlockVolumesPlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetCloudStorageBlockVolumesPlainArgs $;

        public Builder() {
            $ = new GetCloudStorageBlockVolumesPlainArgs();
        }

        public Builder(GetCloudStorageBlockVolumesPlainArgs defaults) {
            $ = new GetCloudStorageBlockVolumesPlainArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param region The region where the volumes reside.
         * 
         * @return builder
         * 
         */
        public Builder region(String region) {
            $.region = region;
            return this;
        }

        /**
         * @param serviceName The id of the public cloud project.
         * 
         * @return builder
         * 
         */
        public Builder serviceName(String serviceName) {
            $.serviceName = serviceName;
            return this;
        }

        public GetCloudStorageBlockVolumesPlainArgs build() {
            if ($.region == null) {
                throw new MissingRequiredPropertyException("GetCloudStorageBlockVolumesPlainArgs", "region");
            }
            if ($.serviceName == null) {
                throw new MissingRequiredPropertyException("GetCloudStorageBlockVolumesPlainArgs", "serviceName");
            }
            return $;
        }
    }

}
