// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.ovhcloud.pulumi.ovh.CloudProject.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class GetKubeCustomizationCiliumHubbleUiBackendResourcesRequestsArgs extends com.pulumi.resources.ResourceArgs {

    public static final GetKubeCustomizationCiliumHubbleUiBackendResourcesRequestsArgs Empty = new GetKubeCustomizationCiliumHubbleUiBackendResourcesRequestsArgs();

    /**
     * CPU request.
     * 
     */
    @Import(name="cpu", required=true)
    private Output<String> cpu;

    /**
     * @return CPU request.
     * 
     */
    public Output<String> cpu() {
        return this.cpu;
    }

    /**
     * Memory request.
     * 
     */
    @Import(name="memory", required=true)
    private Output<String> memory;

    /**
     * @return Memory request.
     * 
     */
    public Output<String> memory() {
        return this.memory;
    }

    private GetKubeCustomizationCiliumHubbleUiBackendResourcesRequestsArgs() {}

    private GetKubeCustomizationCiliumHubbleUiBackendResourcesRequestsArgs(GetKubeCustomizationCiliumHubbleUiBackendResourcesRequestsArgs $) {
        this.cpu = $.cpu;
        this.memory = $.memory;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetKubeCustomizationCiliumHubbleUiBackendResourcesRequestsArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetKubeCustomizationCiliumHubbleUiBackendResourcesRequestsArgs $;

        public Builder() {
            $ = new GetKubeCustomizationCiliumHubbleUiBackendResourcesRequestsArgs();
        }

        public Builder(GetKubeCustomizationCiliumHubbleUiBackendResourcesRequestsArgs defaults) {
            $ = new GetKubeCustomizationCiliumHubbleUiBackendResourcesRequestsArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param cpu CPU request.
         * 
         * @return builder
         * 
         */
        public Builder cpu(Output<String> cpu) {
            $.cpu = cpu;
            return this;
        }

        /**
         * @param cpu CPU request.
         * 
         * @return builder
         * 
         */
        public Builder cpu(String cpu) {
            return cpu(Output.of(cpu));
        }

        /**
         * @param memory Memory request.
         * 
         * @return builder
         * 
         */
        public Builder memory(Output<String> memory) {
            $.memory = memory;
            return this;
        }

        /**
         * @param memory Memory request.
         * 
         * @return builder
         * 
         */
        public Builder memory(String memory) {
            return memory(Output.of(memory));
        }

        public GetKubeCustomizationCiliumHubbleUiBackendResourcesRequestsArgs build() {
            if ($.cpu == null) {
                throw new MissingRequiredPropertyException("GetKubeCustomizationCiliumHubbleUiBackendResourcesRequestsArgs", "cpu");
            }
            if ($.memory == null) {
                throw new MissingRequiredPropertyException("GetKubeCustomizationCiliumHubbleUiBackendResourcesRequestsArgs", "memory");
            }
            return $;
        }
    }

}
