// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Ovh
{
    /// <summary>
    /// Creates a log subscription for a Managed Kubernetes cluster associated with a public cloud project.
    /// 
    /// ## Example Usage
    /// 
    /// Create a log subscription for a Managed Kubernetes cluster.
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Ovh = Pulumi.Ovh;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var stream = Ovh.Dbaas.GetLogsOutputGraylogStream.Invoke(new()
    ///     {
    ///         ServiceName = "ldp-xx-xxxxx",
    ///         Title = "my stream",
    ///     });
    /// 
    ///     var cluster = Ovh.CloudProject.GetKube.Invoke(new()
    ///     {
    ///         ServiceName = "XXXXXX",
    ///         KubeId = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    ///     });
    /// 
    ///     var sub = new Ovh.CloudProjectKubeLogSubscription("sub", new()
    ///     {
    ///         ServiceName = cluster.Apply(getKubeResult =&gt; getKubeResult.ServiceName),
    ///         KubeId = cluster.Apply(getKubeResult =&gt; getKubeResult.Id),
    ///         StreamId = stream.Apply(getLogsOutputGraylogStreamResult =&gt; getLogsOutputGraylogStreamResult.StreamId),
    ///         Kind = "audit",
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// &gt; **Note:** The OVHcloud APIv6 token used by the provider must have `GET` access on the following URI in its token ACL: `/dbaas/logs/*/operation/*`
    /// 
    /// ## Import
    /// 
    /// OVHcloud Managed Kubernetes Service cluster log subscription can be imported using the `service_name`, `kube_id` and `subscription_id` separated by "/" E.g.,
    /// 
    /// bash
    /// 
    /// ```sh
    /// $ pulumi import ovh:index/cloudProjectKubeLogSubscription:CloudProjectKubeLogSubscription sub service_name/kube_id/subscription_id
    /// ```
    /// </summary>
    [OvhResourceType("ovh:index/cloudProjectKubeLogSubscription:CloudProjectKubeLogSubscription")]
    public partial class CloudProjectKubeLogSubscription : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Creation date of the subscription.
        /// </summary>
        [Output("createdAt")]
        public Output<string> CreatedAt { get; private set; } = null!;

        /// <summary>
        /// Log kind name of this subscription. Only `audit` is currently supported.
        /// </summary>
        [Output("kind")]
        public Output<string> Kind { get; private set; } = null!;

        /// <summary>
        /// The id of the managed kubernetes cluster.
        /// </summary>
        [Output("kubeId")]
        public Output<string> KubeId { get; private set; } = null!;

        /// <summary>
        /// Information about the subscribed resource.
        /// </summary>
        [Output("resources")]
        public Output<ImmutableArray<Outputs.CloudProjectKubeLogSubscriptionResource>> Resources { get; private set; } = null!;

        /// <summary>
        /// The id of the public cloud project. If omitted, the `OVH_CLOUD_PROJECT_SERVICE` environment variable is used.
        /// </summary>
        [Output("serviceName")]
        public Output<string> ServiceName { get; private set; } = null!;

        /// <summary>
        /// Id of the target Log data platform stream.
        /// </summary>
        [Output("streamId")]
        public Output<string> StreamId { get; private set; } = null!;

        /// <summary>
        /// ID of the log subscription.
        /// </summary>
        [Output("subscriptionId")]
        public Output<string> SubscriptionId { get; private set; } = null!;

        /// <summary>
        /// Last update date of the subscription.
        /// </summary>
        [Output("updatedAt")]
        public Output<string> UpdatedAt { get; private set; } = null!;


        /// <summary>
        /// Create a CloudProjectKubeLogSubscription resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public CloudProjectKubeLogSubscription(string name, CloudProjectKubeLogSubscriptionArgs args, CustomResourceOptions? options = null)
            : base("ovh:index/cloudProjectKubeLogSubscription:CloudProjectKubeLogSubscription", name, args ?? new CloudProjectKubeLogSubscriptionArgs(), MakeResourceOptions(options, ""))
        {
        }

        private CloudProjectKubeLogSubscription(string name, Input<string> id, CloudProjectKubeLogSubscriptionState? state = null, CustomResourceOptions? options = null)
            : base("ovh:index/cloudProjectKubeLogSubscription:CloudProjectKubeLogSubscription", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/ovh/pulumi-ovh",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing CloudProjectKubeLogSubscription resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static CloudProjectKubeLogSubscription Get(string name, Input<string> id, CloudProjectKubeLogSubscriptionState? state = null, CustomResourceOptions? options = null)
        {
            return new CloudProjectKubeLogSubscription(name, id, state, options);
        }
    }

    public sealed class CloudProjectKubeLogSubscriptionArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Log kind name of this subscription. Only `audit` is currently supported.
        /// </summary>
        [Input("kind", required: true)]
        public Input<string> Kind { get; set; } = null!;

        /// <summary>
        /// The id of the managed kubernetes cluster.
        /// </summary>
        [Input("kubeId", required: true)]
        public Input<string> KubeId { get; set; } = null!;

        /// <summary>
        /// The id of the public cloud project. If omitted, the `OVH_CLOUD_PROJECT_SERVICE` environment variable is used.
        /// </summary>
        [Input("serviceName")]
        public Input<string>? ServiceName { get; set; }

        /// <summary>
        /// Id of the target Log data platform stream.
        /// </summary>
        [Input("streamId", required: true)]
        public Input<string> StreamId { get; set; } = null!;

        public CloudProjectKubeLogSubscriptionArgs()
        {
        }
        public static new CloudProjectKubeLogSubscriptionArgs Empty => new CloudProjectKubeLogSubscriptionArgs();
    }

    public sealed class CloudProjectKubeLogSubscriptionState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Creation date of the subscription.
        /// </summary>
        [Input("createdAt")]
        public Input<string>? CreatedAt { get; set; }

        /// <summary>
        /// Log kind name of this subscription. Only `audit` is currently supported.
        /// </summary>
        [Input("kind")]
        public Input<string>? Kind { get; set; }

        /// <summary>
        /// The id of the managed kubernetes cluster.
        /// </summary>
        [Input("kubeId")]
        public Input<string>? KubeId { get; set; }

        [Input("resources")]
        private InputList<Inputs.CloudProjectKubeLogSubscriptionResourceGetArgs>? _resources;

        /// <summary>
        /// Information about the subscribed resource.
        /// </summary>
        public InputList<Inputs.CloudProjectKubeLogSubscriptionResourceGetArgs> Resources
        {
            get => _resources ?? (_resources = new InputList<Inputs.CloudProjectKubeLogSubscriptionResourceGetArgs>());
            set => _resources = value;
        }

        /// <summary>
        /// The id of the public cloud project. If omitted, the `OVH_CLOUD_PROJECT_SERVICE` environment variable is used.
        /// </summary>
        [Input("serviceName")]
        public Input<string>? ServiceName { get; set; }

        /// <summary>
        /// Id of the target Log data platform stream.
        /// </summary>
        [Input("streamId")]
        public Input<string>? StreamId { get; set; }

        /// <summary>
        /// ID of the log subscription.
        /// </summary>
        [Input("subscriptionId")]
        public Input<string>? SubscriptionId { get; set; }

        /// <summary>
        /// Last update date of the subscription.
        /// </summary>
        [Input("updatedAt")]
        public Input<string>? UpdatedAt { get; set; }

        public CloudProjectKubeLogSubscriptionState()
        {
        }
        public static new CloudProjectKubeLogSubscriptionState Empty => new CloudProjectKubeLogSubscriptionState();
    }
}
