// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Ovh.CloudProject
{
    public static class GetMongoDbPrometheus
    {
        /// <summary>
        /// Use this data source to get information about a prometheus of a MongoDB cluster associated with a public cloud project.
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Ovh = Pulumi.Ovh;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var prometheus = Ovh.CloudProject.GetMongoDbPrometheus.Invoke(new()
        ///     {
        ///         ServiceName = "XXX",
        ///         ClusterId = "ZZZ",
        ///     });
        /// 
        ///     return new Dictionary&lt;string, object?&gt;
        ///     {
        ///         ["name"] = prometheus.Apply(getMongoDbPrometheusResult =&gt; getMongoDbPrometheusResult.Username),
        ///     };
        /// });
        /// ```
        /// </summary>
        public static Task<GetMongoDbPrometheusResult> InvokeAsync(GetMongoDbPrometheusArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetMongoDbPrometheusResult>("ovh:CloudProject/getMongoDbPrometheus:getMongoDbPrometheus", args ?? new GetMongoDbPrometheusArgs(), options.WithDefaults());

        /// <summary>
        /// Use this data source to get information about a prometheus of a MongoDB cluster associated with a public cloud project.
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Ovh = Pulumi.Ovh;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var prometheus = Ovh.CloudProject.GetMongoDbPrometheus.Invoke(new()
        ///     {
        ///         ServiceName = "XXX",
        ///         ClusterId = "ZZZ",
        ///     });
        /// 
        ///     return new Dictionary&lt;string, object?&gt;
        ///     {
        ///         ["name"] = prometheus.Apply(getMongoDbPrometheusResult =&gt; getMongoDbPrometheusResult.Username),
        ///     };
        /// });
        /// ```
        /// </summary>
        public static Output<GetMongoDbPrometheusResult> Invoke(GetMongoDbPrometheusInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetMongoDbPrometheusResult>("ovh:CloudProject/getMongoDbPrometheus:getMongoDbPrometheus", args ?? new GetMongoDbPrometheusInvokeArgs(), options.WithDefaults());

        /// <summary>
        /// Use this data source to get information about a prometheus of a MongoDB cluster associated with a public cloud project.
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Ovh = Pulumi.Ovh;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var prometheus = Ovh.CloudProject.GetMongoDbPrometheus.Invoke(new()
        ///     {
        ///         ServiceName = "XXX",
        ///         ClusterId = "ZZZ",
        ///     });
        /// 
        ///     return new Dictionary&lt;string, object?&gt;
        ///     {
        ///         ["name"] = prometheus.Apply(getMongoDbPrometheusResult =&gt; getMongoDbPrometheusResult.Username),
        ///     };
        /// });
        /// ```
        /// </summary>
        public static Output<GetMongoDbPrometheusResult> Invoke(GetMongoDbPrometheusInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetMongoDbPrometheusResult>("ovh:CloudProject/getMongoDbPrometheus:getMongoDbPrometheus", args ?? new GetMongoDbPrometheusInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetMongoDbPrometheusArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// Cluster ID
        /// </summary>
        [Input("clusterId", required: true)]
        public string ClusterId { get; set; } = null!;

        /// <summary>
        /// The id of the public cloud project. If omitted, the `OVH_CLOUD_PROJECT_SERVICE` environment variable is used.
        /// </summary>
        [Input("serviceName", required: true)]
        public string ServiceName { get; set; } = null!;

        public GetMongoDbPrometheusArgs()
        {
        }
        public static new GetMongoDbPrometheusArgs Empty => new GetMongoDbPrometheusArgs();
    }

    public sealed class GetMongoDbPrometheusInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// Cluster ID
        /// </summary>
        [Input("clusterId", required: true)]
        public Input<string> ClusterId { get; set; } = null!;

        /// <summary>
        /// The id of the public cloud project. If omitted, the `OVH_CLOUD_PROJECT_SERVICE` environment variable is used.
        /// </summary>
        [Input("serviceName", required: true)]
        public Input<string> ServiceName { get; set; } = null!;

        public GetMongoDbPrometheusInvokeArgs()
        {
        }
        public static new GetMongoDbPrometheusInvokeArgs Empty => new GetMongoDbPrometheusInvokeArgs();
    }


    [OutputType]
    public sealed class GetMongoDbPrometheusResult
    {
        /// <summary>
        /// See Argument Reference above.
        /// </summary>
        public readonly string ClusterId;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// See Argument Reference above.
        /// </summary>
        public readonly string ServiceName;
        /// <summary>
        /// Name of the srv domain endpoint.
        /// </summary>
        public readonly string SrvDomain;
        /// <summary>
        /// name of the prometheus user.
        /// </summary>
        public readonly string Username;

        [OutputConstructor]
        private GetMongoDbPrometheusResult(
            string clusterId,

            string id,

            string serviceName,

            string srvDomain,

            string username)
        {
            ClusterId = clusterId;
            Id = id;
            ServiceName = serviceName;
            SrvDomain = srvDomain;
            Username = username;
        }
    }
}
