// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package ovh

import (
	"context"
	"reflect"

	"github.com/ovh/pulumi-ovh/sdk/v2/go/ovh/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Get lifecycle configuration of a S3™* compatible storage container. \* S3 is a trademark filed by Amazon Technologies,Inc. OVHcloud's service is not sponsored by, endorsed by, or otherwise affiliated with Amazon Technologies,Inc.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/ovh/pulumi-ovh/sdk/v2/go/ovh"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := ovh.LookupCloudProjectStorageObjectBucketLifecycleConfiguration(ctx, &ovh.LookupCloudProjectStorageObjectBucketLifecycleConfigurationArgs{
//				ServiceName:   pulumi.StringRef("<public cloud project ID>"),
//				RegionName:    "GRA",
//				ContainerName: "my-bucket",
//			}, nil)
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
func LookupCloudProjectStorageObjectBucketLifecycleConfiguration(ctx *pulumi.Context, args *LookupCloudProjectStorageObjectBucketLifecycleConfigurationArgs, opts ...pulumi.InvokeOption) (*LookupCloudProjectStorageObjectBucketLifecycleConfigurationResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupCloudProjectStorageObjectBucketLifecycleConfigurationResult
	err := ctx.Invoke("ovh:index/getCloudProjectStorageObjectBucketLifecycleConfiguration:getCloudProjectStorageObjectBucketLifecycleConfiguration", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getCloudProjectStorageObjectBucketLifecycleConfiguration.
type LookupCloudProjectStorageObjectBucketLifecycleConfigurationArgs struct {
	// Name of the storage container.
	ContainerName string `pulumi:"containerName"`
	// Region name of the storage container.
	RegionName string `pulumi:"regionName"`
	// The ID of the public cloud project. If omitted, the `OVH_CLOUD_PROJECT_SERVICE` environment variable is used.
	ServiceName *string `pulumi:"serviceName"`
}

// A collection of values returned by getCloudProjectStorageObjectBucketLifecycleConfiguration.
type LookupCloudProjectStorageObjectBucketLifecycleConfigurationResult struct {
	// Name of the storage container.
	ContainerName string `pulumi:"containerName"`
	// Unique identifier for the resource (service*name/region*name/container_name)
	Id string `pulumi:"id"`
	// Region name of the storage container.
	RegionName string `pulumi:"regionName"`
	// List of lifecycle rules.
	Rules []GetCloudProjectStorageObjectBucketLifecycleConfigurationRule `pulumi:"rules"`
	// The ID of the public cloud project. If omitted, the `OVH_CLOUD_PROJECT_SERVICE` environment variable is used.
	ServiceName string `pulumi:"serviceName"`
}

func LookupCloudProjectStorageObjectBucketLifecycleConfigurationOutput(ctx *pulumi.Context, args LookupCloudProjectStorageObjectBucketLifecycleConfigurationOutputArgs, opts ...pulumi.InvokeOption) LookupCloudProjectStorageObjectBucketLifecycleConfigurationResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupCloudProjectStorageObjectBucketLifecycleConfigurationResultOutput, error) {
			args := v.(LookupCloudProjectStorageObjectBucketLifecycleConfigurationArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("ovh:index/getCloudProjectStorageObjectBucketLifecycleConfiguration:getCloudProjectStorageObjectBucketLifecycleConfiguration", args, LookupCloudProjectStorageObjectBucketLifecycleConfigurationResultOutput{}, options).(LookupCloudProjectStorageObjectBucketLifecycleConfigurationResultOutput), nil
		}).(LookupCloudProjectStorageObjectBucketLifecycleConfigurationResultOutput)
}

// A collection of arguments for invoking getCloudProjectStorageObjectBucketLifecycleConfiguration.
type LookupCloudProjectStorageObjectBucketLifecycleConfigurationOutputArgs struct {
	// Name of the storage container.
	ContainerName pulumi.StringInput `pulumi:"containerName"`
	// Region name of the storage container.
	RegionName pulumi.StringInput `pulumi:"regionName"`
	// The ID of the public cloud project. If omitted, the `OVH_CLOUD_PROJECT_SERVICE` environment variable is used.
	ServiceName pulumi.StringPtrInput `pulumi:"serviceName"`
}

func (LookupCloudProjectStorageObjectBucketLifecycleConfigurationOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupCloudProjectStorageObjectBucketLifecycleConfigurationArgs)(nil)).Elem()
}

// A collection of values returned by getCloudProjectStorageObjectBucketLifecycleConfiguration.
type LookupCloudProjectStorageObjectBucketLifecycleConfigurationResultOutput struct{ *pulumi.OutputState }

func (LookupCloudProjectStorageObjectBucketLifecycleConfigurationResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupCloudProjectStorageObjectBucketLifecycleConfigurationResult)(nil)).Elem()
}

func (o LookupCloudProjectStorageObjectBucketLifecycleConfigurationResultOutput) ToLookupCloudProjectStorageObjectBucketLifecycleConfigurationResultOutput() LookupCloudProjectStorageObjectBucketLifecycleConfigurationResultOutput {
	return o
}

func (o LookupCloudProjectStorageObjectBucketLifecycleConfigurationResultOutput) ToLookupCloudProjectStorageObjectBucketLifecycleConfigurationResultOutputWithContext(ctx context.Context) LookupCloudProjectStorageObjectBucketLifecycleConfigurationResultOutput {
	return o
}

// Name of the storage container.
func (o LookupCloudProjectStorageObjectBucketLifecycleConfigurationResultOutput) ContainerName() pulumi.StringOutput {
	return o.ApplyT(func(v LookupCloudProjectStorageObjectBucketLifecycleConfigurationResult) string {
		return v.ContainerName
	}).(pulumi.StringOutput)
}

// Unique identifier for the resource (service*name/region*name/container_name)
func (o LookupCloudProjectStorageObjectBucketLifecycleConfigurationResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupCloudProjectStorageObjectBucketLifecycleConfigurationResult) string { return v.Id }).(pulumi.StringOutput)
}

// Region name of the storage container.
func (o LookupCloudProjectStorageObjectBucketLifecycleConfigurationResultOutput) RegionName() pulumi.StringOutput {
	return o.ApplyT(func(v LookupCloudProjectStorageObjectBucketLifecycleConfigurationResult) string { return v.RegionName }).(pulumi.StringOutput)
}

// List of lifecycle rules.
func (o LookupCloudProjectStorageObjectBucketLifecycleConfigurationResultOutput) Rules() GetCloudProjectStorageObjectBucketLifecycleConfigurationRuleArrayOutput {
	return o.ApplyT(func(v LookupCloudProjectStorageObjectBucketLifecycleConfigurationResult) []GetCloudProjectStorageObjectBucketLifecycleConfigurationRule {
		return v.Rules
	}).(GetCloudProjectStorageObjectBucketLifecycleConfigurationRuleArrayOutput)
}

// The ID of the public cloud project. If omitted, the `OVH_CLOUD_PROJECT_SERVICE` environment variable is used.
func (o LookupCloudProjectStorageObjectBucketLifecycleConfigurationResultOutput) ServiceName() pulumi.StringOutput {
	return o.ApplyT(func(v LookupCloudProjectStorageObjectBucketLifecycleConfigurationResult) string { return v.ServiceName }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupCloudProjectStorageObjectBucketLifecycleConfigurationResultOutput{})
}
