// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.ovhcloud.pulumi.ovh.Dedicated.inputs;

import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetServerBootsPlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetServerBootsPlainArgs Empty = new GetServerBootsPlainArgs();

    /**
     * Filter the value of bootType property (harddisk, rescue, ipxeCustomerScript, internal, network)
     * 
     */
    @Import(name="bootType")
    private @Nullable String bootType;

    /**
     * @return Filter the value of bootType property (harddisk, rescue, ipxeCustomerScript, internal, network)
     * 
     */
    public Optional<String> bootType() {
        return Optional.ofNullable(this.bootType);
    }

    /**
     * Filter the value of kernel property (iPXE script name)
     * 
     */
    @Import(name="kernel")
    private @Nullable String kernel;

    /**
     * @return Filter the value of kernel property (iPXE script name)
     * 
     */
    public Optional<String> kernel() {
        return Optional.ofNullable(this.kernel);
    }

    /**
     * The internal name of your dedicated server.
     * 
     */
    @Import(name="serviceName", required=true)
    private String serviceName;

    /**
     * @return The internal name of your dedicated server.
     * 
     */
    public String serviceName() {
        return this.serviceName;
    }

    private GetServerBootsPlainArgs() {}

    private GetServerBootsPlainArgs(GetServerBootsPlainArgs $) {
        this.bootType = $.bootType;
        this.kernel = $.kernel;
        this.serviceName = $.serviceName;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetServerBootsPlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetServerBootsPlainArgs $;

        public Builder() {
            $ = new GetServerBootsPlainArgs();
        }

        public Builder(GetServerBootsPlainArgs defaults) {
            $ = new GetServerBootsPlainArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param bootType Filter the value of bootType property (harddisk, rescue, ipxeCustomerScript, internal, network)
         * 
         * @return builder
         * 
         */
        public Builder bootType(@Nullable String bootType) {
            $.bootType = bootType;
            return this;
        }

        /**
         * @param kernel Filter the value of kernel property (iPXE script name)
         * 
         * @return builder
         * 
         */
        public Builder kernel(@Nullable String kernel) {
            $.kernel = kernel;
            return this;
        }

        /**
         * @param serviceName The internal name of your dedicated server.
         * 
         * @return builder
         * 
         */
        public Builder serviceName(String serviceName) {
            $.serviceName = serviceName;
            return this;
        }

        public GetServerBootsPlainArgs build() {
            if ($.serviceName == null) {
                throw new MissingRequiredPropertyException("GetServerBootsPlainArgs", "serviceName");
            }
            return $;
        }
    }

}
