// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.ovh.ovh.CloudProjectDatabase.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class GetKafkaUserAccessResult {
    /**
     * @return User cert.
     * 
     */
    private String cert;
    /**
     * @return See Argument Reference above.
     * 
     */
    private String clusterId;
    /**
     * @return The provider-assigned unique ID for this managed resource.
     * 
     */
    private String id;
    /**
     * @return (Sensitive) User key for the cert.
     * 
     */
    private String key;
    /**
     * @return See Argument Reference above.
     * 
     */
    private String serviceName;
    /**
     * @return See Argument Reference above.
     * 
     */
    private String userId;

    private GetKafkaUserAccessResult() {}
    /**
     * @return User cert.
     * 
     */
    public String cert() {
        return this.cert;
    }
    /**
     * @return See Argument Reference above.
     * 
     */
    public String clusterId() {
        return this.clusterId;
    }
    /**
     * @return The provider-assigned unique ID for this managed resource.
     * 
     */
    public String id() {
        return this.id;
    }
    /**
     * @return (Sensitive) User key for the cert.
     * 
     */
    public String key() {
        return this.key;
    }
    /**
     * @return See Argument Reference above.
     * 
     */
    public String serviceName() {
        return this.serviceName;
    }
    /**
     * @return See Argument Reference above.
     * 
     */
    public String userId() {
        return this.userId;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetKafkaUserAccessResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String cert;
        private String clusterId;
        private String id;
        private String key;
        private String serviceName;
        private String userId;
        public Builder() {}
        public Builder(GetKafkaUserAccessResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.cert = defaults.cert;
    	      this.clusterId = defaults.clusterId;
    	      this.id = defaults.id;
    	      this.key = defaults.key;
    	      this.serviceName = defaults.serviceName;
    	      this.userId = defaults.userId;
        }

        @CustomType.Setter
        public Builder cert(String cert) {
            this.cert = Objects.requireNonNull(cert);
            return this;
        }
        @CustomType.Setter
        public Builder clusterId(String clusterId) {
            this.clusterId = Objects.requireNonNull(clusterId);
            return this;
        }
        @CustomType.Setter
        public Builder id(String id) {
            this.id = Objects.requireNonNull(id);
            return this;
        }
        @CustomType.Setter
        public Builder key(String key) {
            this.key = Objects.requireNonNull(key);
            return this;
        }
        @CustomType.Setter
        public Builder serviceName(String serviceName) {
            this.serviceName = Objects.requireNonNull(serviceName);
            return this;
        }
        @CustomType.Setter
        public Builder userId(String userId) {
            this.userId = Objects.requireNonNull(userId);
            return this;
        }
        public GetKafkaUserAccessResult build() {
            final var o = new GetKafkaUserAccessResult();
            o.cert = cert;
            o.clusterId = clusterId;
            o.id = id;
            o.key = key;
            o.serviceName = serviceName;
            o.userId = userId;
            return o;
        }
    }
}
