// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Ovh.Outputs
{

    [OutputType]
    public sealed class GetCloudLoadbalancersLoadbalancerNetworkResult
    {
        /// <summary>
        /// Flavor ID.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// IP address.
        /// </summary>
        public readonly string Ip;
        /// <summary>
        /// Subnet ID.
        /// </summary>
        public readonly string SubnetId;

        [OutputConstructor]
        private GetCloudLoadbalancersLoadbalancerNetworkResult(
            string id,

            string ip,

            string subnetId)
        {
            Id = id;
            Ip = ip;
            SubnetId = subnetId;
        }
    }
}
