// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package dbaas

import (
	"context"
	"reflect"

	"github.com/ovh/pulumi-ovh/sdk/go/ovh/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Use this data source to retrieve information about a DBaas logs output opensearch index.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/ovh/pulumi-ovh/sdk/go/ovh/Dbaas"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := Dbaas.GetLogsOutputOpenSearchIndex(ctx, &dbaas.GetLogsOutputOpenSearchIndexArgs{
//				Name:        "index-name",
//				ServiceName: "ldp-xx-xxxxx",
//			}, nil)
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
func LookupLogsOutputOpenSearchIndex(ctx *pulumi.Context, args *LookupLogsOutputOpenSearchIndexArgs, opts ...pulumi.InvokeOption) (*LookupLogsOutputOpenSearchIndexResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupLogsOutputOpenSearchIndexResult
	err := ctx.Invoke("ovh:Dbaas/getLogsOutputOpenSearchIndex:getLogsOutputOpenSearchIndex", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getLogsOutputOpenSearchIndex.
type LookupLogsOutputOpenSearchIndexArgs struct {
	// Index name
	Name string `pulumi:"name"`
	// Number of shard
	NbShard *int `pulumi:"nbShard"`
	// The service name. It's the ID of your Logs Data Platform instance.
	ServiceName string `pulumi:"serviceName"`
}

// A collection of values returned by getLogsOutputOpenSearchIndex.
type LookupLogsOutputOpenSearchIndexResult struct {
	// If set, notify when size is near 80, 90 or 100 % of its maximum capacity
	AlertNotifyEnabled bool `pulumi:"alertNotifyEnabled"`
	// Index creation
	CreatedAt string `pulumi:"createdAt"`
	// Current index size (in bytes)
	CurrentSize int `pulumi:"currentSize"`
	// Index description
	Description string `pulumi:"description"`
	// The provider-assigned unique ID for this managed resource.
	Id string `pulumi:"id"`
	// Index ID
	IndexId string `pulumi:"indexId"`
	// Indicates if you are allowed to edit entry
	IsEditable bool `pulumi:"isEditable"`
	// Maximum index size (in bytes)
	MaxSize int `pulumi:"maxSize"`
	// Index name
	Name string `pulumi:"name"`
	// Number of shard
	NbShard     int    `pulumi:"nbShard"`
	ServiceName string `pulumi:"serviceName"`
	// Index last update
	UpdatedAt string `pulumi:"updatedAt"`
}

func LookupLogsOutputOpenSearchIndexOutput(ctx *pulumi.Context, args LookupLogsOutputOpenSearchIndexOutputArgs, opts ...pulumi.InvokeOption) LookupLogsOutputOpenSearchIndexResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupLogsOutputOpenSearchIndexResultOutput, error) {
			args := v.(LookupLogsOutputOpenSearchIndexArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("ovh:Dbaas/getLogsOutputOpenSearchIndex:getLogsOutputOpenSearchIndex", args, LookupLogsOutputOpenSearchIndexResultOutput{}, options).(LookupLogsOutputOpenSearchIndexResultOutput), nil
		}).(LookupLogsOutputOpenSearchIndexResultOutput)
}

// A collection of arguments for invoking getLogsOutputOpenSearchIndex.
type LookupLogsOutputOpenSearchIndexOutputArgs struct {
	// Index name
	Name pulumi.StringInput `pulumi:"name"`
	// Number of shard
	NbShard pulumi.IntPtrInput `pulumi:"nbShard"`
	// The service name. It's the ID of your Logs Data Platform instance.
	ServiceName pulumi.StringInput `pulumi:"serviceName"`
}

func (LookupLogsOutputOpenSearchIndexOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupLogsOutputOpenSearchIndexArgs)(nil)).Elem()
}

// A collection of values returned by getLogsOutputOpenSearchIndex.
type LookupLogsOutputOpenSearchIndexResultOutput struct{ *pulumi.OutputState }

func (LookupLogsOutputOpenSearchIndexResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupLogsOutputOpenSearchIndexResult)(nil)).Elem()
}

func (o LookupLogsOutputOpenSearchIndexResultOutput) ToLookupLogsOutputOpenSearchIndexResultOutput() LookupLogsOutputOpenSearchIndexResultOutput {
	return o
}

func (o LookupLogsOutputOpenSearchIndexResultOutput) ToLookupLogsOutputOpenSearchIndexResultOutputWithContext(ctx context.Context) LookupLogsOutputOpenSearchIndexResultOutput {
	return o
}

// If set, notify when size is near 80, 90 or 100 % of its maximum capacity
func (o LookupLogsOutputOpenSearchIndexResultOutput) AlertNotifyEnabled() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupLogsOutputOpenSearchIndexResult) bool { return v.AlertNotifyEnabled }).(pulumi.BoolOutput)
}

// Index creation
func (o LookupLogsOutputOpenSearchIndexResultOutput) CreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v LookupLogsOutputOpenSearchIndexResult) string { return v.CreatedAt }).(pulumi.StringOutput)
}

// Current index size (in bytes)
func (o LookupLogsOutputOpenSearchIndexResultOutput) CurrentSize() pulumi.IntOutput {
	return o.ApplyT(func(v LookupLogsOutputOpenSearchIndexResult) int { return v.CurrentSize }).(pulumi.IntOutput)
}

// Index description
func (o LookupLogsOutputOpenSearchIndexResultOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v LookupLogsOutputOpenSearchIndexResult) string { return v.Description }).(pulumi.StringOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o LookupLogsOutputOpenSearchIndexResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupLogsOutputOpenSearchIndexResult) string { return v.Id }).(pulumi.StringOutput)
}

// Index ID
func (o LookupLogsOutputOpenSearchIndexResultOutput) IndexId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupLogsOutputOpenSearchIndexResult) string { return v.IndexId }).(pulumi.StringOutput)
}

// Indicates if you are allowed to edit entry
func (o LookupLogsOutputOpenSearchIndexResultOutput) IsEditable() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupLogsOutputOpenSearchIndexResult) bool { return v.IsEditable }).(pulumi.BoolOutput)
}

// Maximum index size (in bytes)
func (o LookupLogsOutputOpenSearchIndexResultOutput) MaxSize() pulumi.IntOutput {
	return o.ApplyT(func(v LookupLogsOutputOpenSearchIndexResult) int { return v.MaxSize }).(pulumi.IntOutput)
}

// Index name
func (o LookupLogsOutputOpenSearchIndexResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupLogsOutputOpenSearchIndexResult) string { return v.Name }).(pulumi.StringOutput)
}

// Number of shard
func (o LookupLogsOutputOpenSearchIndexResultOutput) NbShard() pulumi.IntOutput {
	return o.ApplyT(func(v LookupLogsOutputOpenSearchIndexResult) int { return v.NbShard }).(pulumi.IntOutput)
}

func (o LookupLogsOutputOpenSearchIndexResultOutput) ServiceName() pulumi.StringOutput {
	return o.ApplyT(func(v LookupLogsOutputOpenSearchIndexResult) string { return v.ServiceName }).(pulumi.StringOutput)
}

// Index last update
func (o LookupLogsOutputOpenSearchIndexResultOutput) UpdatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v LookupLogsOutputOpenSearchIndexResult) string { return v.UpdatedAt }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupLogsOutputOpenSearchIndexResultOutput{})
}
