// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Ovh.CloudProject.Outputs
{

    [OutputType]
    public sealed class KubeCustomizationCiliumHubble
    {
        /// <summary>
        /// Enable or disable Hubble.
        /// </summary>
        public readonly bool? Enabled;
        /// <summary>
        /// Hubble Relay configuration.
        /// </summary>
        public readonly Outputs.KubeCustomizationCiliumHubbleRelay? Relay;
        /// <summary>
        /// Hubble UI configuration.
        /// </summary>
        public readonly Outputs.KubeCustomizationCiliumHubbleUi? Ui;

        [OutputConstructor]
        private KubeCustomizationCiliumHubble(
            bool? enabled,

            Outputs.KubeCustomizationCiliumHubbleRelay? relay,

            Outputs.KubeCustomizationCiliumHubbleUi? ui)
        {
            Enabled = enabled;
            Relay = relay;
            Ui = ui;
        }
    }
}
