// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Ovh.CloudProjectDatabase
{
    public static class GetDatabaseIntegration
    {
        public static Task<GetDatabaseIntegrationResult> InvokeAsync(GetDatabaseIntegrationArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetDatabaseIntegrationResult>("ovh:CloudProjectDatabase/getDatabaseIntegration:getDatabaseIntegration", args ?? new GetDatabaseIntegrationArgs(), options.WithDefaults());

        public static Output<GetDatabaseIntegrationResult> Invoke(GetDatabaseIntegrationInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetDatabaseIntegrationResult>("ovh:CloudProjectDatabase/getDatabaseIntegration:getDatabaseIntegration", args ?? new GetDatabaseIntegrationInvokeArgs(), options.WithDefaults());

        public static Output<GetDatabaseIntegrationResult> Invoke(GetDatabaseIntegrationInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetDatabaseIntegrationResult>("ovh:CloudProjectDatabase/getDatabaseIntegration:getDatabaseIntegration", args ?? new GetDatabaseIntegrationInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetDatabaseIntegrationArgs : global::Pulumi.InvokeArgs
    {
        [Input("clusterId", required: true)]
        public string ClusterId { get; set; } = null!;

        [Input("engine", required: true)]
        public string Engine { get; set; } = null!;

        [Input("id", required: true)]
        public string Id { get; set; } = null!;

        [Input("serviceName", required: true)]
        public string ServiceName { get; set; } = null!;

        public GetDatabaseIntegrationArgs()
        {
        }
        public static new GetDatabaseIntegrationArgs Empty => new GetDatabaseIntegrationArgs();
    }

    public sealed class GetDatabaseIntegrationInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("clusterId", required: true)]
        public Input<string> ClusterId { get; set; } = null!;

        [Input("engine", required: true)]
        public Input<string> Engine { get; set; } = null!;

        [Input("id", required: true)]
        public Input<string> Id { get; set; } = null!;

        [Input("serviceName", required: true)]
        public Input<string> ServiceName { get; set; } = null!;

        public GetDatabaseIntegrationInvokeArgs()
        {
        }
        public static new GetDatabaseIntegrationInvokeArgs Empty => new GetDatabaseIntegrationInvokeArgs();
    }


    [OutputType]
    public sealed class GetDatabaseIntegrationResult
    {
        public readonly string ClusterId;
        public readonly string DestinationServiceId;
        public readonly string Engine;
        public readonly string Id;
        public readonly ImmutableDictionary<string, string> Parameters;
        public readonly string ServiceName;
        public readonly string SourceServiceId;
        public readonly string Status;
        public readonly string Type;

        [OutputConstructor]
        private GetDatabaseIntegrationResult(
            string clusterId,

            string destinationServiceId,

            string engine,

            string id,

            ImmutableDictionary<string, string> parameters,

            string serviceName,

            string sourceServiceId,

            string status,

            string type)
        {
            ClusterId = clusterId;
            DestinationServiceId = destinationServiceId;
            Engine = engine;
            Id = id;
            Parameters = parameters;
            ServiceName = serviceName;
            SourceServiceId = sourceServiceId;
            Status = status;
            Type = type;
        }
    }
}
