// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package okms

import (
	"context"
	"reflect"

	"github.com/ovh/pulumi-ovh/sdk/v2/go/ovh/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetOkmsResource(ctx *pulumi.Context, args *GetOkmsResourceArgs, opts ...pulumi.InvokeOption) (*GetOkmsResourceResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetOkmsResourceResult
	err := ctx.Invoke("ovh:Okms/getOkmsResource:getOkmsResource", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getOkmsResource.
type GetOkmsResourceArgs struct {
	Id string `pulumi:"id"`
}

// A collection of values returned by getOkmsResource.
type GetOkmsResourceResult struct {
	Iam             GetOkmsResourceIam `pulumi:"iam"`
	Id              string             `pulumi:"id"`
	KmipEndpoint    string             `pulumi:"kmipEndpoint"`
	PublicCa        string             `pulumi:"publicCa"`
	Region          string             `pulumi:"region"`
	RestEndpoint    string             `pulumi:"restEndpoint"`
	SwaggerEndpoint string             `pulumi:"swaggerEndpoint"`
}

func GetOkmsResourceOutput(ctx *pulumi.Context, args GetOkmsResourceOutputArgs, opts ...pulumi.InvokeOption) GetOkmsResourceResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetOkmsResourceResultOutput, error) {
			args := v.(GetOkmsResourceArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("ovh:Okms/getOkmsResource:getOkmsResource", args, GetOkmsResourceResultOutput{}, options).(GetOkmsResourceResultOutput), nil
		}).(GetOkmsResourceResultOutput)
}

// A collection of arguments for invoking getOkmsResource.
type GetOkmsResourceOutputArgs struct {
	Id pulumi.StringInput `pulumi:"id"`
}

func (GetOkmsResourceOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetOkmsResourceArgs)(nil)).Elem()
}

// A collection of values returned by getOkmsResource.
type GetOkmsResourceResultOutput struct{ *pulumi.OutputState }

func (GetOkmsResourceResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetOkmsResourceResult)(nil)).Elem()
}

func (o GetOkmsResourceResultOutput) ToGetOkmsResourceResultOutput() GetOkmsResourceResultOutput {
	return o
}

func (o GetOkmsResourceResultOutput) ToGetOkmsResourceResultOutputWithContext(ctx context.Context) GetOkmsResourceResultOutput {
	return o
}

func (o GetOkmsResourceResultOutput) Iam() GetOkmsResourceIamOutput {
	return o.ApplyT(func(v GetOkmsResourceResult) GetOkmsResourceIam { return v.Iam }).(GetOkmsResourceIamOutput)
}

func (o GetOkmsResourceResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetOkmsResourceResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetOkmsResourceResultOutput) KmipEndpoint() pulumi.StringOutput {
	return o.ApplyT(func(v GetOkmsResourceResult) string { return v.KmipEndpoint }).(pulumi.StringOutput)
}

func (o GetOkmsResourceResultOutput) PublicCa() pulumi.StringOutput {
	return o.ApplyT(func(v GetOkmsResourceResult) string { return v.PublicCa }).(pulumi.StringOutput)
}

func (o GetOkmsResourceResultOutput) Region() pulumi.StringOutput {
	return o.ApplyT(func(v GetOkmsResourceResult) string { return v.Region }).(pulumi.StringOutput)
}

func (o GetOkmsResourceResultOutput) RestEndpoint() pulumi.StringOutput {
	return o.ApplyT(func(v GetOkmsResourceResult) string { return v.RestEndpoint }).(pulumi.StringOutput)
}

func (o GetOkmsResourceResultOutput) SwaggerEndpoint() pulumi.StringOutput {
	return o.ApplyT(func(v GetOkmsResourceResult) string { return v.SwaggerEndpoint }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(GetOkmsResourceResultOutput{})
}
