// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

export function getKubeOidc(args: GetKubeOidcArgs, opts?: pulumi.InvokeOptions): Promise<GetKubeOidcResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("ovh:CloudProject/getKubeOidc:getKubeOidc", {
        "clientId": args.clientId,
        "issuerUrl": args.issuerUrl,
        "kubeId": args.kubeId,
        "oidcCaContent": args.oidcCaContent,
        "oidcGroupsClaims": args.oidcGroupsClaims,
        "oidcGroupsPrefix": args.oidcGroupsPrefix,
        "oidcRequiredClaims": args.oidcRequiredClaims,
        "oidcSigningAlgs": args.oidcSigningAlgs,
        "oidcUsernameClaim": args.oidcUsernameClaim,
        "oidcUsernamePrefix": args.oidcUsernamePrefix,
        "serviceName": args.serviceName,
    }, opts);
}

/**
 * A collection of arguments for invoking getKubeOidc.
 */
export interface GetKubeOidcArgs {
    clientId?: string;
    issuerUrl?: string;
    kubeId: string;
    oidcCaContent?: string;
    oidcGroupsClaims?: string[];
    oidcGroupsPrefix?: string;
    oidcRequiredClaims?: string[];
    oidcSigningAlgs?: string[];
    oidcUsernameClaim?: string;
    oidcUsernamePrefix?: string;
    serviceName: string;
}

/**
 * A collection of values returned by getKubeOidc.
 */
export interface GetKubeOidcResult {
    readonly clientId?: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly issuerUrl?: string;
    readonly kubeId: string;
    readonly oidcCaContent?: string;
    readonly oidcGroupsClaims?: string[];
    readonly oidcGroupsPrefix?: string;
    readonly oidcRequiredClaims?: string[];
    readonly oidcSigningAlgs?: string[];
    readonly oidcUsernameClaim?: string;
    readonly oidcUsernamePrefix?: string;
    readonly serviceName: string;
}
export function getKubeOidcOutput(args: GetKubeOidcOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetKubeOidcResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("ovh:CloudProject/getKubeOidc:getKubeOidc", {
        "clientId": args.clientId,
        "issuerUrl": args.issuerUrl,
        "kubeId": args.kubeId,
        "oidcCaContent": args.oidcCaContent,
        "oidcGroupsClaims": args.oidcGroupsClaims,
        "oidcGroupsPrefix": args.oidcGroupsPrefix,
        "oidcRequiredClaims": args.oidcRequiredClaims,
        "oidcSigningAlgs": args.oidcSigningAlgs,
        "oidcUsernameClaim": args.oidcUsernameClaim,
        "oidcUsernamePrefix": args.oidcUsernamePrefix,
        "serviceName": args.serviceName,
    }, opts);
}

/**
 * A collection of arguments for invoking getKubeOidc.
 */
export interface GetKubeOidcOutputArgs {
    clientId?: pulumi.Input<string>;
    issuerUrl?: pulumi.Input<string>;
    kubeId: pulumi.Input<string>;
    oidcCaContent?: pulumi.Input<string>;
    oidcGroupsClaims?: pulumi.Input<pulumi.Input<string>[]>;
    oidcGroupsPrefix?: pulumi.Input<string>;
    oidcRequiredClaims?: pulumi.Input<pulumi.Input<string>[]>;
    oidcSigningAlgs?: pulumi.Input<pulumi.Input<string>[]>;
    oidcUsernameClaim?: pulumi.Input<string>;
    oidcUsernamePrefix?: pulumi.Input<string>;
    serviceName: pulumi.Input<string>;
}
