// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

export function getRegionLoadBalancerLogSubscriptions(args: GetRegionLoadBalancerLogSubscriptionsArgs, opts?: pulumi.InvokeOptions): Promise<GetRegionLoadBalancerLogSubscriptionsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("ovh:CloudProject/getRegionLoadBalancerLogSubscriptions:getRegionLoadBalancerLogSubscriptions", {
        "kind": args.kind,
        "loadbalancerId": args.loadbalancerId,
        "regionName": args.regionName,
        "serviceName": args.serviceName,
    }, opts);
}

/**
 * A collection of arguments for invoking getRegionLoadBalancerLogSubscriptions.
 */
export interface GetRegionLoadBalancerLogSubscriptionsArgs {
    kind?: string;
    loadbalancerId: string;
    regionName: string;
    serviceName: string;
}

/**
 * A collection of values returned by getRegionLoadBalancerLogSubscriptions.
 */
export interface GetRegionLoadBalancerLogSubscriptionsResult {
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly kind?: string;
    readonly loadbalancerId: string;
    readonly regionName: string;
    readonly serviceName: string;
    readonly subscriptionIds: string[];
}
export function getRegionLoadBalancerLogSubscriptionsOutput(args: GetRegionLoadBalancerLogSubscriptionsOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetRegionLoadBalancerLogSubscriptionsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("ovh:CloudProject/getRegionLoadBalancerLogSubscriptions:getRegionLoadBalancerLogSubscriptions", {
        "kind": args.kind,
        "loadbalancerId": args.loadbalancerId,
        "regionName": args.regionName,
        "serviceName": args.serviceName,
    }, opts);
}

/**
 * A collection of arguments for invoking getRegionLoadBalancerLogSubscriptions.
 */
export interface GetRegionLoadBalancerLogSubscriptionsOutputArgs {
    kind?: pulumi.Input<string>;
    loadbalancerId: pulumi.Input<string>;
    regionName: pulumi.Input<string>;
    serviceName: pulumi.Input<string>;
}
