# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = [
    'VrackservicesCurrentStateArgs',
    'VrackservicesCurrentStateArgsDict',
    'VrackservicesCurrentStateSubnetArgs',
    'VrackservicesCurrentStateSubnetArgsDict',
    'VrackservicesCurrentStateSubnetServiceEndpointArgs',
    'VrackservicesCurrentStateSubnetServiceEndpointArgsDict',
    'VrackservicesCurrentStateSubnetServiceEndpointEndpointArgs',
    'VrackservicesCurrentStateSubnetServiceEndpointEndpointArgsDict',
    'VrackservicesCurrentStateSubnetServiceRangeArgs',
    'VrackservicesCurrentStateSubnetServiceRangeArgsDict',
    'VrackservicesCurrentTaskArgs',
    'VrackservicesCurrentTaskArgsDict',
    'VrackservicesIamArgs',
    'VrackservicesIamArgsDict',
    'VrackservicesOrderArgs',
    'VrackservicesOrderArgsDict',
    'VrackservicesOrderDetailArgs',
    'VrackservicesOrderDetailArgsDict',
    'VrackservicesPlanArgs',
    'VrackservicesPlanArgsDict',
    'VrackservicesPlanConfigurationArgs',
    'VrackservicesPlanConfigurationArgsDict',
    'VrackservicesPlanOptionArgs',
    'VrackservicesPlanOptionArgsDict',
    'VrackservicesPlanOptionConfigurationArgs',
    'VrackservicesPlanOptionConfigurationArgsDict',
    'VrackservicesTargetSpecArgs',
    'VrackservicesTargetSpecArgsDict',
    'VrackservicesTargetSpecSubnetArgs',
    'VrackservicesTargetSpecSubnetArgsDict',
    'VrackservicesTargetSpecSubnetServiceEndpointArgs',
    'VrackservicesTargetSpecSubnetServiceEndpointArgsDict',
    'VrackservicesTargetSpecSubnetServiceRangeArgs',
    'VrackservicesTargetSpecSubnetServiceRangeArgsDict',
]

MYPY = False

if not MYPY:
    class VrackservicesCurrentStateArgsDict(TypedDict):
        product_status: NotRequired[pulumi.Input[_builtins.str]]
        """
        Product status of the vRack Services
        """
        region: NotRequired[pulumi.Input[_builtins.str]]
        """
        Region of the vRack Services. List of compatible regions can be retrieved from /reference/region
        """
        subnets: NotRequired[pulumi.Input[Sequence[pulumi.Input['VrackservicesCurrentStateSubnetArgsDict']]]]
        """
        Subnets of the current vRack Services
        """
elif False:
    VrackservicesCurrentStateArgsDict: TypeAlias = Mapping[str, Any]

@pulumi.input_type
class VrackservicesCurrentStateArgs:
    def __init__(__self__, *,
                 product_status: Optional[pulumi.Input[_builtins.str]] = None,
                 region: Optional[pulumi.Input[_builtins.str]] = None,
                 subnets: Optional[pulumi.Input[Sequence[pulumi.Input['VrackservicesCurrentStateSubnetArgs']]]] = None):
        """
        :param pulumi.Input[_builtins.str] product_status: Product status of the vRack Services
        :param pulumi.Input[_builtins.str] region: Region of the vRack Services. List of compatible regions can be retrieved from /reference/region
        :param pulumi.Input[Sequence[pulumi.Input['VrackservicesCurrentStateSubnetArgs']]] subnets: Subnets of the current vRack Services
        """
        if product_status is not None:
            pulumi.set(__self__, "product_status", product_status)
        if region is not None:
            pulumi.set(__self__, "region", region)
        if subnets is not None:
            pulumi.set(__self__, "subnets", subnets)

    @_builtins.property
    @pulumi.getter(name="productStatus")
    def product_status(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Product status of the vRack Services
        """
        return pulumi.get(self, "product_status")

    @product_status.setter
    def product_status(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "product_status", value)

    @_builtins.property
    @pulumi.getter
    def region(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Region of the vRack Services. List of compatible regions can be retrieved from /reference/region
        """
        return pulumi.get(self, "region")

    @region.setter
    def region(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "region", value)

    @_builtins.property
    @pulumi.getter
    def subnets(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['VrackservicesCurrentStateSubnetArgs']]]]:
        """
        Subnets of the current vRack Services
        """
        return pulumi.get(self, "subnets")

    @subnets.setter
    def subnets(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['VrackservicesCurrentStateSubnetArgs']]]]):
        pulumi.set(self, "subnets", value)


if not MYPY:
    class VrackservicesCurrentStateSubnetArgsDict(TypedDict):
        cidr: NotRequired[pulumi.Input[_builtins.str]]
        """
        IP address range of the subnet in CIDR format
        """
        display_name: NotRequired[pulumi.Input[_builtins.str]]
        """
        Display name of the subnet
        """
        service_endpoints: NotRequired[pulumi.Input[Sequence[pulumi.Input['VrackservicesCurrentStateSubnetServiceEndpointArgsDict']]]]
        """
        Service endpoints of the subnet
        """
        service_range: NotRequired[pulumi.Input['VrackservicesCurrentStateSubnetServiceRangeArgsDict']]
        """
        Defines a smaller subnet dedicated to the managed services IPs
        """
        vlan: NotRequired[pulumi.Input[_builtins.float]]
        """
        Unique inner VLAN that allows subnets segregation
        """
elif False:
    VrackservicesCurrentStateSubnetArgsDict: TypeAlias = Mapping[str, Any]

@pulumi.input_type
class VrackservicesCurrentStateSubnetArgs:
    def __init__(__self__, *,
                 cidr: Optional[pulumi.Input[_builtins.str]] = None,
                 display_name: Optional[pulumi.Input[_builtins.str]] = None,
                 service_endpoints: Optional[pulumi.Input[Sequence[pulumi.Input['VrackservicesCurrentStateSubnetServiceEndpointArgs']]]] = None,
                 service_range: Optional[pulumi.Input['VrackservicesCurrentStateSubnetServiceRangeArgs']] = None,
                 vlan: Optional[pulumi.Input[_builtins.float]] = None):
        """
        :param pulumi.Input[_builtins.str] cidr: IP address range of the subnet in CIDR format
        :param pulumi.Input[_builtins.str] display_name: Display name of the subnet
        :param pulumi.Input[Sequence[pulumi.Input['VrackservicesCurrentStateSubnetServiceEndpointArgs']]] service_endpoints: Service endpoints of the subnet
        :param pulumi.Input['VrackservicesCurrentStateSubnetServiceRangeArgs'] service_range: Defines a smaller subnet dedicated to the managed services IPs
        :param pulumi.Input[_builtins.float] vlan: Unique inner VLAN that allows subnets segregation
        """
        if cidr is not None:
            pulumi.set(__self__, "cidr", cidr)
        if display_name is not None:
            pulumi.set(__self__, "display_name", display_name)
        if service_endpoints is not None:
            pulumi.set(__self__, "service_endpoints", service_endpoints)
        if service_range is not None:
            pulumi.set(__self__, "service_range", service_range)
        if vlan is not None:
            pulumi.set(__self__, "vlan", vlan)

    @_builtins.property
    @pulumi.getter
    def cidr(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        IP address range of the subnet in CIDR format
        """
        return pulumi.get(self, "cidr")

    @cidr.setter
    def cidr(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "cidr", value)

    @_builtins.property
    @pulumi.getter(name="displayName")
    def display_name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Display name of the subnet
        """
        return pulumi.get(self, "display_name")

    @display_name.setter
    def display_name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "display_name", value)

    @_builtins.property
    @pulumi.getter(name="serviceEndpoints")
    def service_endpoints(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['VrackservicesCurrentStateSubnetServiceEndpointArgs']]]]:
        """
        Service endpoints of the subnet
        """
        return pulumi.get(self, "service_endpoints")

    @service_endpoints.setter
    def service_endpoints(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['VrackservicesCurrentStateSubnetServiceEndpointArgs']]]]):
        pulumi.set(self, "service_endpoints", value)

    @_builtins.property
    @pulumi.getter(name="serviceRange")
    def service_range(self) -> Optional[pulumi.Input['VrackservicesCurrentStateSubnetServiceRangeArgs']]:
        """
        Defines a smaller subnet dedicated to the managed services IPs
        """
        return pulumi.get(self, "service_range")

    @service_range.setter
    def service_range(self, value: Optional[pulumi.Input['VrackservicesCurrentStateSubnetServiceRangeArgs']]):
        pulumi.set(self, "service_range", value)

    @_builtins.property
    @pulumi.getter
    def vlan(self) -> Optional[pulumi.Input[_builtins.float]]:
        """
        Unique inner VLAN that allows subnets segregation
        """
        return pulumi.get(self, "vlan")

    @vlan.setter
    def vlan(self, value: Optional[pulumi.Input[_builtins.float]]):
        pulumi.set(self, "vlan", value)


if not MYPY:
    class VrackservicesCurrentStateSubnetServiceEndpointArgsDict(TypedDict):
        endpoints: NotRequired[pulumi.Input[Sequence[pulumi.Input['VrackservicesCurrentStateSubnetServiceEndpointEndpointArgsDict']]]]
        """
        Endpoints representing the IPs assigned to the managed services
        """
        managed_service_urn: NotRequired[pulumi.Input[_builtins.str]]
        """
        IAM Resource URN of the managed service. Compatible managed service types are listed by /reference/compatibleManagedServiceType call.
        """
elif False:
    VrackservicesCurrentStateSubnetServiceEndpointArgsDict: TypeAlias = Mapping[str, Any]

@pulumi.input_type
class VrackservicesCurrentStateSubnetServiceEndpointArgs:
    def __init__(__self__, *,
                 endpoints: Optional[pulumi.Input[Sequence[pulumi.Input['VrackservicesCurrentStateSubnetServiceEndpointEndpointArgs']]]] = None,
                 managed_service_urn: Optional[pulumi.Input[_builtins.str]] = None):
        """
        :param pulumi.Input[Sequence[pulumi.Input['VrackservicesCurrentStateSubnetServiceEndpointEndpointArgs']]] endpoints: Endpoints representing the IPs assigned to the managed services
        :param pulumi.Input[_builtins.str] managed_service_urn: IAM Resource URN of the managed service. Compatible managed service types are listed by /reference/compatibleManagedServiceType call.
        """
        if endpoints is not None:
            pulumi.set(__self__, "endpoints", endpoints)
        if managed_service_urn is not None:
            pulumi.set(__self__, "managed_service_urn", managed_service_urn)

    @_builtins.property
    @pulumi.getter
    def endpoints(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['VrackservicesCurrentStateSubnetServiceEndpointEndpointArgs']]]]:
        """
        Endpoints representing the IPs assigned to the managed services
        """
        return pulumi.get(self, "endpoints")

    @endpoints.setter
    def endpoints(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['VrackservicesCurrentStateSubnetServiceEndpointEndpointArgs']]]]):
        pulumi.set(self, "endpoints", value)

    @_builtins.property
    @pulumi.getter(name="managedServiceUrn")
    def managed_service_urn(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        IAM Resource URN of the managed service. Compatible managed service types are listed by /reference/compatibleManagedServiceType call.
        """
        return pulumi.get(self, "managed_service_urn")

    @managed_service_urn.setter
    def managed_service_urn(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "managed_service_urn", value)


if not MYPY:
    class VrackservicesCurrentStateSubnetServiceEndpointEndpointArgsDict(TypedDict):
        description: NotRequired[pulumi.Input[_builtins.str]]
        """
        IP description defined in the managed service
        """
        ip: NotRequired[pulumi.Input[_builtins.str]]
        """
        IP address assigned by OVHcloud
        """
elif False:
    VrackservicesCurrentStateSubnetServiceEndpointEndpointArgsDict: TypeAlias = Mapping[str, Any]

@pulumi.input_type
class VrackservicesCurrentStateSubnetServiceEndpointEndpointArgs:
    def __init__(__self__, *,
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 ip: Optional[pulumi.Input[_builtins.str]] = None):
        """
        :param pulumi.Input[_builtins.str] description: IP description defined in the managed service
        :param pulumi.Input[_builtins.str] ip: IP address assigned by OVHcloud
        """
        if description is not None:
            pulumi.set(__self__, "description", description)
        if ip is not None:
            pulumi.set(__self__, "ip", ip)

    @_builtins.property
    @pulumi.getter
    def description(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        IP description defined in the managed service
        """
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "description", value)

    @_builtins.property
    @pulumi.getter
    def ip(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        IP address assigned by OVHcloud
        """
        return pulumi.get(self, "ip")

    @ip.setter
    def ip(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "ip", value)


if not MYPY:
    class VrackservicesCurrentStateSubnetServiceRangeArgsDict(TypedDict):
        cidr: NotRequired[pulumi.Input[_builtins.str]]
        """
        CIDR dedicated to the subnet's services
        """
        remaining_ips: NotRequired[pulumi.Input[_builtins.float]]
        """
        Number of remaining IPs in the service range
        """
        reserved_ips: NotRequired[pulumi.Input[_builtins.float]]
        """
        Number of service range IPs reserved by OVHcloud
        """
        used_ips: NotRequired[pulumi.Input[_builtins.float]]
        """
        Number of service range IPs assigned to the managed services
        """
elif False:
    VrackservicesCurrentStateSubnetServiceRangeArgsDict: TypeAlias = Mapping[str, Any]

@pulumi.input_type
class VrackservicesCurrentStateSubnetServiceRangeArgs:
    def __init__(__self__, *,
                 cidr: Optional[pulumi.Input[_builtins.str]] = None,
                 remaining_ips: Optional[pulumi.Input[_builtins.float]] = None,
                 reserved_ips: Optional[pulumi.Input[_builtins.float]] = None,
                 used_ips: Optional[pulumi.Input[_builtins.float]] = None):
        """
        :param pulumi.Input[_builtins.str] cidr: CIDR dedicated to the subnet's services
        :param pulumi.Input[_builtins.float] remaining_ips: Number of remaining IPs in the service range
        :param pulumi.Input[_builtins.float] reserved_ips: Number of service range IPs reserved by OVHcloud
        :param pulumi.Input[_builtins.float] used_ips: Number of service range IPs assigned to the managed services
        """
        if cidr is not None:
            pulumi.set(__self__, "cidr", cidr)
        if remaining_ips is not None:
            pulumi.set(__self__, "remaining_ips", remaining_ips)
        if reserved_ips is not None:
            pulumi.set(__self__, "reserved_ips", reserved_ips)
        if used_ips is not None:
            pulumi.set(__self__, "used_ips", used_ips)

    @_builtins.property
    @pulumi.getter
    def cidr(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        CIDR dedicated to the subnet's services
        """
        return pulumi.get(self, "cidr")

    @cidr.setter
    def cidr(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "cidr", value)

    @_builtins.property
    @pulumi.getter(name="remainingIps")
    def remaining_ips(self) -> Optional[pulumi.Input[_builtins.float]]:
        """
        Number of remaining IPs in the service range
        """
        return pulumi.get(self, "remaining_ips")

    @remaining_ips.setter
    def remaining_ips(self, value: Optional[pulumi.Input[_builtins.float]]):
        pulumi.set(self, "remaining_ips", value)

    @_builtins.property
    @pulumi.getter(name="reservedIps")
    def reserved_ips(self) -> Optional[pulumi.Input[_builtins.float]]:
        """
        Number of service range IPs reserved by OVHcloud
        """
        return pulumi.get(self, "reserved_ips")

    @reserved_ips.setter
    def reserved_ips(self, value: Optional[pulumi.Input[_builtins.float]]):
        pulumi.set(self, "reserved_ips", value)

    @_builtins.property
    @pulumi.getter(name="usedIps")
    def used_ips(self) -> Optional[pulumi.Input[_builtins.float]]:
        """
        Number of service range IPs assigned to the managed services
        """
        return pulumi.get(self, "used_ips")

    @used_ips.setter
    def used_ips(self, value: Optional[pulumi.Input[_builtins.float]]):
        pulumi.set(self, "used_ips", value)


if not MYPY:
    class VrackservicesCurrentTaskArgsDict(TypedDict):
        id: NotRequired[pulumi.Input[_builtins.str]]
        """
        Identifier of the current task
        """
        link: NotRequired[pulumi.Input[_builtins.str]]
        """
        Link to the related resource
        """
        status: NotRequired[pulumi.Input[_builtins.str]]
        """
        Current global status of the current task
        """
        type: NotRequired[pulumi.Input[_builtins.str]]
        """
        Type of the current task
        """
elif False:
    VrackservicesCurrentTaskArgsDict: TypeAlias = Mapping[str, Any]

@pulumi.input_type
class VrackservicesCurrentTaskArgs:
    def __init__(__self__, *,
                 id: Optional[pulumi.Input[_builtins.str]] = None,
                 link: Optional[pulumi.Input[_builtins.str]] = None,
                 status: Optional[pulumi.Input[_builtins.str]] = None,
                 type: Optional[pulumi.Input[_builtins.str]] = None):
        """
        :param pulumi.Input[_builtins.str] id: Identifier of the current task
        :param pulumi.Input[_builtins.str] link: Link to the related resource
        :param pulumi.Input[_builtins.str] status: Current global status of the current task
        :param pulumi.Input[_builtins.str] type: Type of the current task
        """
        if id is not None:
            pulumi.set(__self__, "id", id)
        if link is not None:
            pulumi.set(__self__, "link", link)
        if status is not None:
            pulumi.set(__self__, "status", status)
        if type is not None:
            pulumi.set(__self__, "type", type)

    @_builtins.property
    @pulumi.getter
    def id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Identifier of the current task
        """
        return pulumi.get(self, "id")

    @id.setter
    def id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "id", value)

    @_builtins.property
    @pulumi.getter
    def link(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Link to the related resource
        """
        return pulumi.get(self, "link")

    @link.setter
    def link(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "link", value)

    @_builtins.property
    @pulumi.getter
    def status(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Current global status of the current task
        """
        return pulumi.get(self, "status")

    @status.setter
    def status(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "status", value)

    @_builtins.property
    @pulumi.getter
    def type(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Type of the current task
        """
        return pulumi.get(self, "type")

    @type.setter
    def type(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "type", value)


if not MYPY:
    class VrackservicesIamArgsDict(TypedDict):
        display_name: NotRequired[pulumi.Input[_builtins.str]]
        """
        Resource display name
        """
        id: NotRequired[pulumi.Input[_builtins.str]]
        """
        Unique identifier of the resource
        """
        tags: NotRequired[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]
        """
        Resource tags. Tags that were internally computed are prefixed with ovh:
        """
        urn: NotRequired[pulumi.Input[_builtins.str]]
        """
        Unique resource name used in policies
        """
elif False:
    VrackservicesIamArgsDict: TypeAlias = Mapping[str, Any]

@pulumi.input_type
class VrackservicesIamArgs:
    def __init__(__self__, *,
                 display_name: Optional[pulumi.Input[_builtins.str]] = None,
                 id: Optional[pulumi.Input[_builtins.str]] = None,
                 tags: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 urn: Optional[pulumi.Input[_builtins.str]] = None):
        """
        :param pulumi.Input[_builtins.str] display_name: Resource display name
        :param pulumi.Input[_builtins.str] id: Unique identifier of the resource
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] tags: Resource tags. Tags that were internally computed are prefixed with ovh:
        :param pulumi.Input[_builtins.str] urn: Unique resource name used in policies
        """
        if display_name is not None:
            pulumi.set(__self__, "display_name", display_name)
        if id is not None:
            pulumi.set(__self__, "id", id)
        if tags is not None:
            pulumi.set(__self__, "tags", tags)
        if urn is not None:
            pulumi.set(__self__, "urn", urn)

    @_builtins.property
    @pulumi.getter(name="displayName")
    def display_name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Resource display name
        """
        return pulumi.get(self, "display_name")

    @display_name.setter
    def display_name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "display_name", value)

    @_builtins.property
    @pulumi.getter
    def id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Unique identifier of the resource
        """
        return pulumi.get(self, "id")

    @id.setter
    def id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "id", value)

    @_builtins.property
    @pulumi.getter
    def tags(self) -> Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]:
        """
        Resource tags. Tags that were internally computed are prefixed with ovh:
        """
        return pulumi.get(self, "tags")

    @tags.setter
    def tags(self, value: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "tags", value)

    @_builtins.property
    @pulumi.getter
    def urn(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Unique resource name used in policies
        """
        return pulumi.get(self, "urn")

    @urn.setter
    def urn(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "urn", value)


if not MYPY:
    class VrackservicesOrderArgsDict(TypedDict):
        date: NotRequired[pulumi.Input[_builtins.str]]
        details: NotRequired[pulumi.Input[Sequence[pulumi.Input['VrackservicesOrderDetailArgsDict']]]]
        expiration_date: NotRequired[pulumi.Input[_builtins.str]]
        order_id: NotRequired[pulumi.Input[_builtins.float]]
elif False:
    VrackservicesOrderArgsDict: TypeAlias = Mapping[str, Any]

@pulumi.input_type
class VrackservicesOrderArgs:
    def __init__(__self__, *,
                 date: Optional[pulumi.Input[_builtins.str]] = None,
                 details: Optional[pulumi.Input[Sequence[pulumi.Input['VrackservicesOrderDetailArgs']]]] = None,
                 expiration_date: Optional[pulumi.Input[_builtins.str]] = None,
                 order_id: Optional[pulumi.Input[_builtins.float]] = None):
        if date is not None:
            pulumi.set(__self__, "date", date)
        if details is not None:
            pulumi.set(__self__, "details", details)
        if expiration_date is not None:
            pulumi.set(__self__, "expiration_date", expiration_date)
        if order_id is not None:
            pulumi.set(__self__, "order_id", order_id)

    @_builtins.property
    @pulumi.getter
    def date(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "date")

    @date.setter
    def date(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "date", value)

    @_builtins.property
    @pulumi.getter
    def details(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['VrackservicesOrderDetailArgs']]]]:
        return pulumi.get(self, "details")

    @details.setter
    def details(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['VrackservicesOrderDetailArgs']]]]):
        pulumi.set(self, "details", value)

    @_builtins.property
    @pulumi.getter(name="expirationDate")
    def expiration_date(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "expiration_date")

    @expiration_date.setter
    def expiration_date(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "expiration_date", value)

    @_builtins.property
    @pulumi.getter(name="orderId")
    def order_id(self) -> Optional[pulumi.Input[_builtins.float]]:
        return pulumi.get(self, "order_id")

    @order_id.setter
    def order_id(self, value: Optional[pulumi.Input[_builtins.float]]):
        pulumi.set(self, "order_id", value)


if not MYPY:
    class VrackservicesOrderDetailArgsDict(TypedDict):
        description: NotRequired[pulumi.Input[_builtins.str]]
        detail_type: NotRequired[pulumi.Input[_builtins.str]]
        """
        Product type of item in order
        """
        domain: NotRequired[pulumi.Input[_builtins.str]]
        order_detail_id: NotRequired[pulumi.Input[_builtins.float]]
        quantity: NotRequired[pulumi.Input[_builtins.str]]
elif False:
    VrackservicesOrderDetailArgsDict: TypeAlias = Mapping[str, Any]

@pulumi.input_type
class VrackservicesOrderDetailArgs:
    def __init__(__self__, *,
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 detail_type: Optional[pulumi.Input[_builtins.str]] = None,
                 domain: Optional[pulumi.Input[_builtins.str]] = None,
                 order_detail_id: Optional[pulumi.Input[_builtins.float]] = None,
                 quantity: Optional[pulumi.Input[_builtins.str]] = None):
        """
        :param pulumi.Input[_builtins.str] detail_type: Product type of item in order
        """
        if description is not None:
            pulumi.set(__self__, "description", description)
        if detail_type is not None:
            pulumi.set(__self__, "detail_type", detail_type)
        if domain is not None:
            pulumi.set(__self__, "domain", domain)
        if order_detail_id is not None:
            pulumi.set(__self__, "order_detail_id", order_detail_id)
        if quantity is not None:
            pulumi.set(__self__, "quantity", quantity)

    @_builtins.property
    @pulumi.getter
    def description(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "description", value)

    @_builtins.property
    @pulumi.getter(name="detailType")
    def detail_type(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Product type of item in order
        """
        return pulumi.get(self, "detail_type")

    @detail_type.setter
    def detail_type(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "detail_type", value)

    @_builtins.property
    @pulumi.getter
    def domain(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "domain")

    @domain.setter
    def domain(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "domain", value)

    @_builtins.property
    @pulumi.getter(name="orderDetailId")
    def order_detail_id(self) -> Optional[pulumi.Input[_builtins.float]]:
        return pulumi.get(self, "order_detail_id")

    @order_detail_id.setter
    def order_detail_id(self, value: Optional[pulumi.Input[_builtins.float]]):
        pulumi.set(self, "order_detail_id", value)

    @_builtins.property
    @pulumi.getter
    def quantity(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "quantity")

    @quantity.setter
    def quantity(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "quantity", value)


if not MYPY:
    class VrackservicesPlanArgsDict(TypedDict):
        duration: pulumi.Input[_builtins.str]
        """
        Duration selected for the purchase of the product
        """
        plan_code: pulumi.Input[_builtins.str]
        """
        Identifier of the option offer
        """
        pricing_mode: pulumi.Input[_builtins.str]
        """
        Pricing mode selected for the purchase of the product
        """
        configurations: NotRequired[pulumi.Input[Sequence[pulumi.Input['VrackservicesPlanConfigurationArgsDict']]]]
        item_id: NotRequired[pulumi.Input[_builtins.float]]
        """
        Cart item to be linked
        """
        quantity: NotRequired[pulumi.Input[_builtins.float]]
        """
        Quantity of product desired
        """
elif False:
    VrackservicesPlanArgsDict: TypeAlias = Mapping[str, Any]

@pulumi.input_type
class VrackservicesPlanArgs:
    def __init__(__self__, *,
                 duration: pulumi.Input[_builtins.str],
                 plan_code: pulumi.Input[_builtins.str],
                 pricing_mode: pulumi.Input[_builtins.str],
                 configurations: Optional[pulumi.Input[Sequence[pulumi.Input['VrackservicesPlanConfigurationArgs']]]] = None,
                 item_id: Optional[pulumi.Input[_builtins.float]] = None,
                 quantity: Optional[pulumi.Input[_builtins.float]] = None):
        """
        :param pulumi.Input[_builtins.str] duration: Duration selected for the purchase of the product
        :param pulumi.Input[_builtins.str] plan_code: Identifier of the option offer
        :param pulumi.Input[_builtins.str] pricing_mode: Pricing mode selected for the purchase of the product
        :param pulumi.Input[_builtins.float] item_id: Cart item to be linked
        :param pulumi.Input[_builtins.float] quantity: Quantity of product desired
        """
        pulumi.set(__self__, "duration", duration)
        pulumi.set(__self__, "plan_code", plan_code)
        pulumi.set(__self__, "pricing_mode", pricing_mode)
        if configurations is not None:
            pulumi.set(__self__, "configurations", configurations)
        if item_id is not None:
            pulumi.set(__self__, "item_id", item_id)
        if quantity is not None:
            pulumi.set(__self__, "quantity", quantity)

    @_builtins.property
    @pulumi.getter
    def duration(self) -> pulumi.Input[_builtins.str]:
        """
        Duration selected for the purchase of the product
        """
        return pulumi.get(self, "duration")

    @duration.setter
    def duration(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "duration", value)

    @_builtins.property
    @pulumi.getter(name="planCode")
    def plan_code(self) -> pulumi.Input[_builtins.str]:
        """
        Identifier of the option offer
        """
        return pulumi.get(self, "plan_code")

    @plan_code.setter
    def plan_code(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "plan_code", value)

    @_builtins.property
    @pulumi.getter(name="pricingMode")
    def pricing_mode(self) -> pulumi.Input[_builtins.str]:
        """
        Pricing mode selected for the purchase of the product
        """
        return pulumi.get(self, "pricing_mode")

    @pricing_mode.setter
    def pricing_mode(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "pricing_mode", value)

    @_builtins.property
    @pulumi.getter
    def configurations(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['VrackservicesPlanConfigurationArgs']]]]:
        return pulumi.get(self, "configurations")

    @configurations.setter
    def configurations(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['VrackservicesPlanConfigurationArgs']]]]):
        pulumi.set(self, "configurations", value)

    @_builtins.property
    @pulumi.getter(name="itemId")
    def item_id(self) -> Optional[pulumi.Input[_builtins.float]]:
        """
        Cart item to be linked
        """
        return pulumi.get(self, "item_id")

    @item_id.setter
    def item_id(self, value: Optional[pulumi.Input[_builtins.float]]):
        pulumi.set(self, "item_id", value)

    @_builtins.property
    @pulumi.getter
    def quantity(self) -> Optional[pulumi.Input[_builtins.float]]:
        """
        Quantity of product desired
        """
        return pulumi.get(self, "quantity")

    @quantity.setter
    def quantity(self, value: Optional[pulumi.Input[_builtins.float]]):
        pulumi.set(self, "quantity", value)


if not MYPY:
    class VrackservicesPlanConfigurationArgsDict(TypedDict):
        label: pulumi.Input[_builtins.str]
        """
        Label for your configuration item
        """
        value: pulumi.Input[_builtins.str]
        """
        Value or resource URL on API.OVH.COM of your configuration item
        """
elif False:
    VrackservicesPlanConfigurationArgsDict: TypeAlias = Mapping[str, Any]

@pulumi.input_type
class VrackservicesPlanConfigurationArgs:
    def __init__(__self__, *,
                 label: pulumi.Input[_builtins.str],
                 value: pulumi.Input[_builtins.str]):
        """
        :param pulumi.Input[_builtins.str] label: Label for your configuration item
        :param pulumi.Input[_builtins.str] value: Value or resource URL on API.OVH.COM of your configuration item
        """
        pulumi.set(__self__, "label", label)
        pulumi.set(__self__, "value", value)

    @_builtins.property
    @pulumi.getter
    def label(self) -> pulumi.Input[_builtins.str]:
        """
        Label for your configuration item
        """
        return pulumi.get(self, "label")

    @label.setter
    def label(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "label", value)

    @_builtins.property
    @pulumi.getter
    def value(self) -> pulumi.Input[_builtins.str]:
        """
        Value or resource URL on API.OVH.COM of your configuration item
        """
        return pulumi.get(self, "value")

    @value.setter
    def value(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "value", value)


if not MYPY:
    class VrackservicesPlanOptionArgsDict(TypedDict):
        duration: pulumi.Input[_builtins.str]
        """
        Duration selected for the purchase of the product
        """
        plan_code: pulumi.Input[_builtins.str]
        """
        Identifier of the option offer
        """
        pricing_mode: pulumi.Input[_builtins.str]
        """
        Pricing mode selected for the purchase of the product
        """
        quantity: pulumi.Input[_builtins.float]
        """
        Quantity of product desired
        """
        configurations: NotRequired[pulumi.Input[Sequence[pulumi.Input['VrackservicesPlanOptionConfigurationArgsDict']]]]
elif False:
    VrackservicesPlanOptionArgsDict: TypeAlias = Mapping[str, Any]

@pulumi.input_type
class VrackservicesPlanOptionArgs:
    def __init__(__self__, *,
                 duration: pulumi.Input[_builtins.str],
                 plan_code: pulumi.Input[_builtins.str],
                 pricing_mode: pulumi.Input[_builtins.str],
                 quantity: pulumi.Input[_builtins.float],
                 configurations: Optional[pulumi.Input[Sequence[pulumi.Input['VrackservicesPlanOptionConfigurationArgs']]]] = None):
        """
        :param pulumi.Input[_builtins.str] duration: Duration selected for the purchase of the product
        :param pulumi.Input[_builtins.str] plan_code: Identifier of the option offer
        :param pulumi.Input[_builtins.str] pricing_mode: Pricing mode selected for the purchase of the product
        :param pulumi.Input[_builtins.float] quantity: Quantity of product desired
        """
        pulumi.set(__self__, "duration", duration)
        pulumi.set(__self__, "plan_code", plan_code)
        pulumi.set(__self__, "pricing_mode", pricing_mode)
        pulumi.set(__self__, "quantity", quantity)
        if configurations is not None:
            pulumi.set(__self__, "configurations", configurations)

    @_builtins.property
    @pulumi.getter
    def duration(self) -> pulumi.Input[_builtins.str]:
        """
        Duration selected for the purchase of the product
        """
        return pulumi.get(self, "duration")

    @duration.setter
    def duration(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "duration", value)

    @_builtins.property
    @pulumi.getter(name="planCode")
    def plan_code(self) -> pulumi.Input[_builtins.str]:
        """
        Identifier of the option offer
        """
        return pulumi.get(self, "plan_code")

    @plan_code.setter
    def plan_code(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "plan_code", value)

    @_builtins.property
    @pulumi.getter(name="pricingMode")
    def pricing_mode(self) -> pulumi.Input[_builtins.str]:
        """
        Pricing mode selected for the purchase of the product
        """
        return pulumi.get(self, "pricing_mode")

    @pricing_mode.setter
    def pricing_mode(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "pricing_mode", value)

    @_builtins.property
    @pulumi.getter
    def quantity(self) -> pulumi.Input[_builtins.float]:
        """
        Quantity of product desired
        """
        return pulumi.get(self, "quantity")

    @quantity.setter
    def quantity(self, value: pulumi.Input[_builtins.float]):
        pulumi.set(self, "quantity", value)

    @_builtins.property
    @pulumi.getter
    def configurations(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['VrackservicesPlanOptionConfigurationArgs']]]]:
        return pulumi.get(self, "configurations")

    @configurations.setter
    def configurations(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['VrackservicesPlanOptionConfigurationArgs']]]]):
        pulumi.set(self, "configurations", value)


if not MYPY:
    class VrackservicesPlanOptionConfigurationArgsDict(TypedDict):
        label: pulumi.Input[_builtins.str]
        """
        Label for your configuration item
        """
        value: pulumi.Input[_builtins.str]
        """
        Value or resource URL on API.OVH.COM of your configuration item
        """
elif False:
    VrackservicesPlanOptionConfigurationArgsDict: TypeAlias = Mapping[str, Any]

@pulumi.input_type
class VrackservicesPlanOptionConfigurationArgs:
    def __init__(__self__, *,
                 label: pulumi.Input[_builtins.str],
                 value: pulumi.Input[_builtins.str]):
        """
        :param pulumi.Input[_builtins.str] label: Label for your configuration item
        :param pulumi.Input[_builtins.str] value: Value or resource URL on API.OVH.COM of your configuration item
        """
        pulumi.set(__self__, "label", label)
        pulumi.set(__self__, "value", value)

    @_builtins.property
    @pulumi.getter
    def label(self) -> pulumi.Input[_builtins.str]:
        """
        Label for your configuration item
        """
        return pulumi.get(self, "label")

    @label.setter
    def label(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "label", value)

    @_builtins.property
    @pulumi.getter
    def value(self) -> pulumi.Input[_builtins.str]:
        """
        Value or resource URL on API.OVH.COM of your configuration item
        """
        return pulumi.get(self, "value")

    @value.setter
    def value(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "value", value)


if not MYPY:
    class VrackservicesTargetSpecArgsDict(TypedDict):
        subnets: pulumi.Input[Sequence[pulumi.Input['VrackservicesTargetSpecSubnetArgsDict']]]
        """
        Target specification of the subnets. Maximum one subnet per vRack Services
        """
elif False:
    VrackservicesTargetSpecArgsDict: TypeAlias = Mapping[str, Any]

@pulumi.input_type
class VrackservicesTargetSpecArgs:
    def __init__(__self__, *,
                 subnets: pulumi.Input[Sequence[pulumi.Input['VrackservicesTargetSpecSubnetArgs']]]):
        """
        :param pulumi.Input[Sequence[pulumi.Input['VrackservicesTargetSpecSubnetArgs']]] subnets: Target specification of the subnets. Maximum one subnet per vRack Services
        """
        pulumi.set(__self__, "subnets", subnets)

    @_builtins.property
    @pulumi.getter
    def subnets(self) -> pulumi.Input[Sequence[pulumi.Input['VrackservicesTargetSpecSubnetArgs']]]:
        """
        Target specification of the subnets. Maximum one subnet per vRack Services
        """
        return pulumi.get(self, "subnets")

    @subnets.setter
    def subnets(self, value: pulumi.Input[Sequence[pulumi.Input['VrackservicesTargetSpecSubnetArgs']]]):
        pulumi.set(self, "subnets", value)


if not MYPY:
    class VrackservicesTargetSpecSubnetArgsDict(TypedDict):
        cidr: pulumi.Input[_builtins.str]
        """
        IPv4 CIDR notation (e.g., 192.0.2.0/24)
        """
        service_endpoints: pulumi.Input[Sequence[pulumi.Input['VrackservicesTargetSpecSubnetServiceEndpointArgsDict']]]
        """
        Target specification of the Service Endpoints
        """
        service_range: pulumi.Input['VrackservicesTargetSpecSubnetServiceRangeArgsDict']
        """
        Target specification of the range dedicated to the subnet's services
        """
        display_name: NotRequired[pulumi.Input[_builtins.str]]
        """
        Display name of the subnet. Format must follow `^[a-zA-Z0-9-_.]{0,40}$`
        """
        vlan: NotRequired[pulumi.Input[_builtins.float]]
        """
        Unique inner VLAN that allows subnets segregation. Authorized values: [2 - 4094] and `null` (untagged traffic)
        """
elif False:
    VrackservicesTargetSpecSubnetArgsDict: TypeAlias = Mapping[str, Any]

@pulumi.input_type
class VrackservicesTargetSpecSubnetArgs:
    def __init__(__self__, *,
                 cidr: pulumi.Input[_builtins.str],
                 service_endpoints: pulumi.Input[Sequence[pulumi.Input['VrackservicesTargetSpecSubnetServiceEndpointArgs']]],
                 service_range: pulumi.Input['VrackservicesTargetSpecSubnetServiceRangeArgs'],
                 display_name: Optional[pulumi.Input[_builtins.str]] = None,
                 vlan: Optional[pulumi.Input[_builtins.float]] = None):
        """
        :param pulumi.Input[_builtins.str] cidr: IPv4 CIDR notation (e.g., 192.0.2.0/24)
        :param pulumi.Input[Sequence[pulumi.Input['VrackservicesTargetSpecSubnetServiceEndpointArgs']]] service_endpoints: Target specification of the Service Endpoints
        :param pulumi.Input['VrackservicesTargetSpecSubnetServiceRangeArgs'] service_range: Target specification of the range dedicated to the subnet's services
        :param pulumi.Input[_builtins.str] display_name: Display name of the subnet. Format must follow `^[a-zA-Z0-9-_.]{0,40}$`
        :param pulumi.Input[_builtins.float] vlan: Unique inner VLAN that allows subnets segregation. Authorized values: [2 - 4094] and `null` (untagged traffic)
        """
        pulumi.set(__self__, "cidr", cidr)
        pulumi.set(__self__, "service_endpoints", service_endpoints)
        pulumi.set(__self__, "service_range", service_range)
        if display_name is not None:
            pulumi.set(__self__, "display_name", display_name)
        if vlan is not None:
            pulumi.set(__self__, "vlan", vlan)

    @_builtins.property
    @pulumi.getter
    def cidr(self) -> pulumi.Input[_builtins.str]:
        """
        IPv4 CIDR notation (e.g., 192.0.2.0/24)
        """
        return pulumi.get(self, "cidr")

    @cidr.setter
    def cidr(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "cidr", value)

    @_builtins.property
    @pulumi.getter(name="serviceEndpoints")
    def service_endpoints(self) -> pulumi.Input[Sequence[pulumi.Input['VrackservicesTargetSpecSubnetServiceEndpointArgs']]]:
        """
        Target specification of the Service Endpoints
        """
        return pulumi.get(self, "service_endpoints")

    @service_endpoints.setter
    def service_endpoints(self, value: pulumi.Input[Sequence[pulumi.Input['VrackservicesTargetSpecSubnetServiceEndpointArgs']]]):
        pulumi.set(self, "service_endpoints", value)

    @_builtins.property
    @pulumi.getter(name="serviceRange")
    def service_range(self) -> pulumi.Input['VrackservicesTargetSpecSubnetServiceRangeArgs']:
        """
        Target specification of the range dedicated to the subnet's services
        """
        return pulumi.get(self, "service_range")

    @service_range.setter
    def service_range(self, value: pulumi.Input['VrackservicesTargetSpecSubnetServiceRangeArgs']):
        pulumi.set(self, "service_range", value)

    @_builtins.property
    @pulumi.getter(name="displayName")
    def display_name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Display name of the subnet. Format must follow `^[a-zA-Z0-9-_.]{0,40}$`
        """
        return pulumi.get(self, "display_name")

    @display_name.setter
    def display_name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "display_name", value)

    @_builtins.property
    @pulumi.getter
    def vlan(self) -> Optional[pulumi.Input[_builtins.float]]:
        """
        Unique inner VLAN that allows subnets segregation. Authorized values: [2 - 4094] and `null` (untagged traffic)
        """
        return pulumi.get(self, "vlan")

    @vlan.setter
    def vlan(self, value: Optional[pulumi.Input[_builtins.float]]):
        pulumi.set(self, "vlan", value)


if not MYPY:
    class VrackservicesTargetSpecSubnetServiceEndpointArgsDict(TypedDict):
        managed_service_urn: pulumi.Input[_builtins.str]
        """
        IAM Resource URN of the managed service. Managed service Region must match vRack Services Region. Compatible managed service types are listed by /reference/compatibleManagedServiceType call
        """
elif False:
    VrackservicesTargetSpecSubnetServiceEndpointArgsDict: TypeAlias = Mapping[str, Any]

@pulumi.input_type
class VrackservicesTargetSpecSubnetServiceEndpointArgs:
    def __init__(__self__, *,
                 managed_service_urn: pulumi.Input[_builtins.str]):
        """
        :param pulumi.Input[_builtins.str] managed_service_urn: IAM Resource URN of the managed service. Managed service Region must match vRack Services Region. Compatible managed service types are listed by /reference/compatibleManagedServiceType call
        """
        pulumi.set(__self__, "managed_service_urn", managed_service_urn)

    @_builtins.property
    @pulumi.getter(name="managedServiceUrn")
    def managed_service_urn(self) -> pulumi.Input[_builtins.str]:
        """
        IAM Resource URN of the managed service. Managed service Region must match vRack Services Region. Compatible managed service types are listed by /reference/compatibleManagedServiceType call
        """
        return pulumi.get(self, "managed_service_urn")

    @managed_service_urn.setter
    def managed_service_urn(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "managed_service_urn", value)


if not MYPY:
    class VrackservicesTargetSpecSubnetServiceRangeArgsDict(TypedDict):
        cidr: pulumi.Input[_builtins.str]
        """
        IPv4 CIDR notation (e.g., 192.0.2.0/24)
        """
elif False:
    VrackservicesTargetSpecSubnetServiceRangeArgsDict: TypeAlias = Mapping[str, Any]

@pulumi.input_type
class VrackservicesTargetSpecSubnetServiceRangeArgs:
    def __init__(__self__, *,
                 cidr: pulumi.Input[_builtins.str]):
        """
        :param pulumi.Input[_builtins.str] cidr: IPv4 CIDR notation (e.g., 192.0.2.0/24)
        """
        pulumi.set(__self__, "cidr", cidr)

    @_builtins.property
    @pulumi.getter
    def cidr(self) -> pulumi.Input[_builtins.str]:
        """
        IPv4 CIDR notation (e.g., 192.0.2.0/24)
        """
        return pulumi.get(self, "cidr")

    @cidr.setter
    def cidr(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "cidr", value)


