# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs
from ._inputs import *

__all__ = ['CloudLoadbalancerListenerArgs', 'CloudLoadbalancerListener']

@pulumi.input_type
class CloudLoadbalancerListenerArgs:
    def __init__(__self__, *,
                 loadbalancer_id: pulumi.Input[_builtins.str],
                 protocol: pulumi.Input[_builtins.str],
                 protocol_port: pulumi.Input[_builtins.int],
                 service_name: pulumi.Input[_builtins.str],
                 allowed_cidrs: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 connection_limit: Optional[pulumi.Input[_builtins.int]] = None,
                 default_pool_id: Optional[pulumi.Input[_builtins.str]] = None,
                 default_tls_container_ref: Optional[pulumi.Input[_builtins.str]] = None,
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 insert_headers: Optional[pulumi.Input['CloudLoadbalancerListenerInsertHeadersArgs']] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 sni_container_refs: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 timeout_client_data: Optional[pulumi.Input[_builtins.int]] = None,
                 timeout_member_connect: Optional[pulumi.Input[_builtins.int]] = None,
                 timeout_member_data: Optional[pulumi.Input[_builtins.int]] = None,
                 timeout_tcp_inspect: Optional[pulumi.Input[_builtins.int]] = None,
                 tls_versions: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None):
        """
        The set of arguments for constructing a CloudLoadbalancerListener resource.
        :param pulumi.Input[_builtins.str] loadbalancer_id: ID of the load balancer. **Changing this value recreates the resource.**
        :param pulumi.Input[_builtins.str] protocol: Protocol of the listener (`HTTP`, `HTTPS`, `SCTP`, `TCP`, `TERMINATED_HTTPS`, `UDP`). **Changing this value recreates the resource.**
        :param pulumi.Input[_builtins.int] protocol_port: Port number the listener listens on. **Changing this value recreates the resource.**
        :param pulumi.Input[_builtins.str] service_name: Service name of the resource representing the id of the cloud project. **Changing this value recreates the resource.**
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] allowed_cidrs: List of CIDRs allowed to access the listener.
        :param pulumi.Input[_builtins.int] connection_limit: Maximum number of connections allowed. If omitted, the value assigned by the API is stored in the state.
        :param pulumi.Input[_builtins.str] default_pool_id: ID of the default pool for this listener (see `CloudLoadbalancerPool`). If omitted, the value assigned by the API is stored in the state.
        :param pulumi.Input[_builtins.str] default_tls_container_ref: Reference to the default TLS container.
        :param pulumi.Input[_builtins.str] description: Description of the listener.
        :param pulumi.Input['CloudLoadbalancerListenerInsertHeadersArgs'] insert_headers: Headers to insert into requests:
        :param pulumi.Input[_builtins.str] name: Name of the listener.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] sni_container_refs: List of SNI container references.
        :param pulumi.Input[_builtins.int] timeout_client_data: Timeout for client data in milliseconds. If omitted, the default assigned by the API is stored in the state.
        :param pulumi.Input[_builtins.int] timeout_member_connect: Timeout for member connection in milliseconds. If omitted, the default assigned by the API is stored in the state.
        :param pulumi.Input[_builtins.int] timeout_member_data: Timeout for member data in milliseconds. If omitted, the default assigned by the API is stored in the state.
        :param pulumi.Input[_builtins.int] timeout_tcp_inspect: Timeout for TCP inspect in milliseconds. If omitted, the default assigned by the API is stored in the state.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] tls_versions: List of TLS versions allowed.
        """
        pulumi.set(__self__, "loadbalancer_id", loadbalancer_id)
        pulumi.set(__self__, "protocol", protocol)
        pulumi.set(__self__, "protocol_port", protocol_port)
        pulumi.set(__self__, "service_name", service_name)
        if allowed_cidrs is not None:
            pulumi.set(__self__, "allowed_cidrs", allowed_cidrs)
        if connection_limit is not None:
            pulumi.set(__self__, "connection_limit", connection_limit)
        if default_pool_id is not None:
            pulumi.set(__self__, "default_pool_id", default_pool_id)
        if default_tls_container_ref is not None:
            pulumi.set(__self__, "default_tls_container_ref", default_tls_container_ref)
        if description is not None:
            pulumi.set(__self__, "description", description)
        if insert_headers is not None:
            pulumi.set(__self__, "insert_headers", insert_headers)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if sni_container_refs is not None:
            pulumi.set(__self__, "sni_container_refs", sni_container_refs)
        if timeout_client_data is not None:
            pulumi.set(__self__, "timeout_client_data", timeout_client_data)
        if timeout_member_connect is not None:
            pulumi.set(__self__, "timeout_member_connect", timeout_member_connect)
        if timeout_member_data is not None:
            pulumi.set(__self__, "timeout_member_data", timeout_member_data)
        if timeout_tcp_inspect is not None:
            pulumi.set(__self__, "timeout_tcp_inspect", timeout_tcp_inspect)
        if tls_versions is not None:
            pulumi.set(__self__, "tls_versions", tls_versions)

    @_builtins.property
    @pulumi.getter(name="loadbalancerId")
    def loadbalancer_id(self) -> pulumi.Input[_builtins.str]:
        """
        ID of the load balancer. **Changing this value recreates the resource.**
        """
        return pulumi.get(self, "loadbalancer_id")

    @loadbalancer_id.setter
    def loadbalancer_id(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "loadbalancer_id", value)

    @_builtins.property
    @pulumi.getter
    def protocol(self) -> pulumi.Input[_builtins.str]:
        """
        Protocol of the listener (`HTTP`, `HTTPS`, `SCTP`, `TCP`, `TERMINATED_HTTPS`, `UDP`). **Changing this value recreates the resource.**
        """
        return pulumi.get(self, "protocol")

    @protocol.setter
    def protocol(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "protocol", value)

    @_builtins.property
    @pulumi.getter(name="protocolPort")
    def protocol_port(self) -> pulumi.Input[_builtins.int]:
        """
        Port number the listener listens on. **Changing this value recreates the resource.**
        """
        return pulumi.get(self, "protocol_port")

    @protocol_port.setter
    def protocol_port(self, value: pulumi.Input[_builtins.int]):
        pulumi.set(self, "protocol_port", value)

    @_builtins.property
    @pulumi.getter(name="serviceName")
    def service_name(self) -> pulumi.Input[_builtins.str]:
        """
        Service name of the resource representing the id of the cloud project. **Changing this value recreates the resource.**
        """
        return pulumi.get(self, "service_name")

    @service_name.setter
    def service_name(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "service_name", value)

    @_builtins.property
    @pulumi.getter(name="allowedCidrs")
    def allowed_cidrs(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        List of CIDRs allowed to access the listener.
        """
        return pulumi.get(self, "allowed_cidrs")

    @allowed_cidrs.setter
    def allowed_cidrs(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "allowed_cidrs", value)

    @_builtins.property
    @pulumi.getter(name="connectionLimit")
    def connection_limit(self) -> Optional[pulumi.Input[_builtins.int]]:
        """
        Maximum number of connections allowed. If omitted, the value assigned by the API is stored in the state.
        """
        return pulumi.get(self, "connection_limit")

    @connection_limit.setter
    def connection_limit(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "connection_limit", value)

    @_builtins.property
    @pulumi.getter(name="defaultPoolId")
    def default_pool_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        ID of the default pool for this listener (see `CloudLoadbalancerPool`). If omitted, the value assigned by the API is stored in the state.
        """
        return pulumi.get(self, "default_pool_id")

    @default_pool_id.setter
    def default_pool_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "default_pool_id", value)

    @_builtins.property
    @pulumi.getter(name="defaultTlsContainerRef")
    def default_tls_container_ref(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Reference to the default TLS container.
        """
        return pulumi.get(self, "default_tls_container_ref")

    @default_tls_container_ref.setter
    def default_tls_container_ref(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "default_tls_container_ref", value)

    @_builtins.property
    @pulumi.getter
    def description(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Description of the listener.
        """
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "description", value)

    @_builtins.property
    @pulumi.getter(name="insertHeaders")
    def insert_headers(self) -> Optional[pulumi.Input['CloudLoadbalancerListenerInsertHeadersArgs']]:
        """
        Headers to insert into requests:
        """
        return pulumi.get(self, "insert_headers")

    @insert_headers.setter
    def insert_headers(self, value: Optional[pulumi.Input['CloudLoadbalancerListenerInsertHeadersArgs']]):
        pulumi.set(self, "insert_headers", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Name of the listener.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter(name="sniContainerRefs")
    def sni_container_refs(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        List of SNI container references.
        """
        return pulumi.get(self, "sni_container_refs")

    @sni_container_refs.setter
    def sni_container_refs(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "sni_container_refs", value)

    @_builtins.property
    @pulumi.getter(name="timeoutClientData")
    def timeout_client_data(self) -> Optional[pulumi.Input[_builtins.int]]:
        """
        Timeout for client data in milliseconds. If omitted, the default assigned by the API is stored in the state.
        """
        return pulumi.get(self, "timeout_client_data")

    @timeout_client_data.setter
    def timeout_client_data(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "timeout_client_data", value)

    @_builtins.property
    @pulumi.getter(name="timeoutMemberConnect")
    def timeout_member_connect(self) -> Optional[pulumi.Input[_builtins.int]]:
        """
        Timeout for member connection in milliseconds. If omitted, the default assigned by the API is stored in the state.
        """
        return pulumi.get(self, "timeout_member_connect")

    @timeout_member_connect.setter
    def timeout_member_connect(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "timeout_member_connect", value)

    @_builtins.property
    @pulumi.getter(name="timeoutMemberData")
    def timeout_member_data(self) -> Optional[pulumi.Input[_builtins.int]]:
        """
        Timeout for member data in milliseconds. If omitted, the default assigned by the API is stored in the state.
        """
        return pulumi.get(self, "timeout_member_data")

    @timeout_member_data.setter
    def timeout_member_data(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "timeout_member_data", value)

    @_builtins.property
    @pulumi.getter(name="timeoutTcpInspect")
    def timeout_tcp_inspect(self) -> Optional[pulumi.Input[_builtins.int]]:
        """
        Timeout for TCP inspect in milliseconds. If omitted, the default assigned by the API is stored in the state.
        """
        return pulumi.get(self, "timeout_tcp_inspect")

    @timeout_tcp_inspect.setter
    def timeout_tcp_inspect(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "timeout_tcp_inspect", value)

    @_builtins.property
    @pulumi.getter(name="tlsVersions")
    def tls_versions(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        List of TLS versions allowed.
        """
        return pulumi.get(self, "tls_versions")

    @tls_versions.setter
    def tls_versions(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "tls_versions", value)


@pulumi.input_type
class _CloudLoadbalancerListenerState:
    def __init__(__self__, *,
                 allowed_cidrs: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 checksum: Optional[pulumi.Input[_builtins.str]] = None,
                 connection_limit: Optional[pulumi.Input[_builtins.int]] = None,
                 created_at: Optional[pulumi.Input[_builtins.str]] = None,
                 current_state: Optional[pulumi.Input['CloudLoadbalancerListenerCurrentStateArgs']] = None,
                 default_pool_id: Optional[pulumi.Input[_builtins.str]] = None,
                 default_tls_container_ref: Optional[pulumi.Input[_builtins.str]] = None,
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 insert_headers: Optional[pulumi.Input['CloudLoadbalancerListenerInsertHeadersArgs']] = None,
                 loadbalancer_id: Optional[pulumi.Input[_builtins.str]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 protocol: Optional[pulumi.Input[_builtins.str]] = None,
                 protocol_port: Optional[pulumi.Input[_builtins.int]] = None,
                 resource_status: Optional[pulumi.Input[_builtins.str]] = None,
                 service_name: Optional[pulumi.Input[_builtins.str]] = None,
                 sni_container_refs: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 timeout_client_data: Optional[pulumi.Input[_builtins.int]] = None,
                 timeout_member_connect: Optional[pulumi.Input[_builtins.int]] = None,
                 timeout_member_data: Optional[pulumi.Input[_builtins.int]] = None,
                 timeout_tcp_inspect: Optional[pulumi.Input[_builtins.int]] = None,
                 tls_versions: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 updated_at: Optional[pulumi.Input[_builtins.str]] = None):
        """
        Input properties used for looking up and filtering CloudLoadbalancerListener resources.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] allowed_cidrs: List of CIDRs allowed to access the listener.
        :param pulumi.Input[_builtins.str] checksum: Computed hash representing the current target specification value.
        :param pulumi.Input[_builtins.int] connection_limit: Maximum number of connections allowed. If omitted, the value assigned by the API is stored in the state.
        :param pulumi.Input[_builtins.str] created_at: Creation date of the listener.
        :param pulumi.Input['CloudLoadbalancerListenerCurrentStateArgs'] current_state: Current state of the listener:
        :param pulumi.Input[_builtins.str] default_pool_id: ID of the default pool for this listener (see `CloudLoadbalancerPool`). If omitted, the value assigned by the API is stored in the state.
        :param pulumi.Input[_builtins.str] default_tls_container_ref: Reference to the default TLS container.
        :param pulumi.Input[_builtins.str] description: Description of the listener.
        :param pulumi.Input['CloudLoadbalancerListenerInsertHeadersArgs'] insert_headers: Headers to insert into requests:
        :param pulumi.Input[_builtins.str] loadbalancer_id: ID of the load balancer. **Changing this value recreates the resource.**
        :param pulumi.Input[_builtins.str] name: Name of the listener.
        :param pulumi.Input[_builtins.str] protocol: Protocol of the listener (`HTTP`, `HTTPS`, `SCTP`, `TCP`, `TERMINATED_HTTPS`, `UDP`). **Changing this value recreates the resource.**
        :param pulumi.Input[_builtins.int] protocol_port: Port number the listener listens on. **Changing this value recreates the resource.**
        :param pulumi.Input[_builtins.str] resource_status: Listener readiness in the system (`CREATING`, `DELETING`, `ERROR`, `OUT_OF_SYNC`, `READY`, `UPDATING`).
        :param pulumi.Input[_builtins.str] service_name: Service name of the resource representing the id of the cloud project. **Changing this value recreates the resource.**
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] sni_container_refs: List of SNI container references.
        :param pulumi.Input[_builtins.int] timeout_client_data: Timeout for client data in milliseconds. If omitted, the default assigned by the API is stored in the state.
        :param pulumi.Input[_builtins.int] timeout_member_connect: Timeout for member connection in milliseconds. If omitted, the default assigned by the API is stored in the state.
        :param pulumi.Input[_builtins.int] timeout_member_data: Timeout for member data in milliseconds. If omitted, the default assigned by the API is stored in the state.
        :param pulumi.Input[_builtins.int] timeout_tcp_inspect: Timeout for TCP inspect in milliseconds. If omitted, the default assigned by the API is stored in the state.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] tls_versions: List of TLS versions allowed.
        :param pulumi.Input[_builtins.str] updated_at: Last update date of the listener.
        """
        if allowed_cidrs is not None:
            pulumi.set(__self__, "allowed_cidrs", allowed_cidrs)
        if checksum is not None:
            pulumi.set(__self__, "checksum", checksum)
        if connection_limit is not None:
            pulumi.set(__self__, "connection_limit", connection_limit)
        if created_at is not None:
            pulumi.set(__self__, "created_at", created_at)
        if current_state is not None:
            pulumi.set(__self__, "current_state", current_state)
        if default_pool_id is not None:
            pulumi.set(__self__, "default_pool_id", default_pool_id)
        if default_tls_container_ref is not None:
            pulumi.set(__self__, "default_tls_container_ref", default_tls_container_ref)
        if description is not None:
            pulumi.set(__self__, "description", description)
        if insert_headers is not None:
            pulumi.set(__self__, "insert_headers", insert_headers)
        if loadbalancer_id is not None:
            pulumi.set(__self__, "loadbalancer_id", loadbalancer_id)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if protocol is not None:
            pulumi.set(__self__, "protocol", protocol)
        if protocol_port is not None:
            pulumi.set(__self__, "protocol_port", protocol_port)
        if resource_status is not None:
            pulumi.set(__self__, "resource_status", resource_status)
        if service_name is not None:
            pulumi.set(__self__, "service_name", service_name)
        if sni_container_refs is not None:
            pulumi.set(__self__, "sni_container_refs", sni_container_refs)
        if timeout_client_data is not None:
            pulumi.set(__self__, "timeout_client_data", timeout_client_data)
        if timeout_member_connect is not None:
            pulumi.set(__self__, "timeout_member_connect", timeout_member_connect)
        if timeout_member_data is not None:
            pulumi.set(__self__, "timeout_member_data", timeout_member_data)
        if timeout_tcp_inspect is not None:
            pulumi.set(__self__, "timeout_tcp_inspect", timeout_tcp_inspect)
        if tls_versions is not None:
            pulumi.set(__self__, "tls_versions", tls_versions)
        if updated_at is not None:
            pulumi.set(__self__, "updated_at", updated_at)

    @_builtins.property
    @pulumi.getter(name="allowedCidrs")
    def allowed_cidrs(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        List of CIDRs allowed to access the listener.
        """
        return pulumi.get(self, "allowed_cidrs")

    @allowed_cidrs.setter
    def allowed_cidrs(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "allowed_cidrs", value)

    @_builtins.property
    @pulumi.getter
    def checksum(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Computed hash representing the current target specification value.
        """
        return pulumi.get(self, "checksum")

    @checksum.setter
    def checksum(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "checksum", value)

    @_builtins.property
    @pulumi.getter(name="connectionLimit")
    def connection_limit(self) -> Optional[pulumi.Input[_builtins.int]]:
        """
        Maximum number of connections allowed. If omitted, the value assigned by the API is stored in the state.
        """
        return pulumi.get(self, "connection_limit")

    @connection_limit.setter
    def connection_limit(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "connection_limit", value)

    @_builtins.property
    @pulumi.getter(name="createdAt")
    def created_at(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Creation date of the listener.
        """
        return pulumi.get(self, "created_at")

    @created_at.setter
    def created_at(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "created_at", value)

    @_builtins.property
    @pulumi.getter(name="currentState")
    def current_state(self) -> Optional[pulumi.Input['CloudLoadbalancerListenerCurrentStateArgs']]:
        """
        Current state of the listener:
        """
        return pulumi.get(self, "current_state")

    @current_state.setter
    def current_state(self, value: Optional[pulumi.Input['CloudLoadbalancerListenerCurrentStateArgs']]):
        pulumi.set(self, "current_state", value)

    @_builtins.property
    @pulumi.getter(name="defaultPoolId")
    def default_pool_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        ID of the default pool for this listener (see `CloudLoadbalancerPool`). If omitted, the value assigned by the API is stored in the state.
        """
        return pulumi.get(self, "default_pool_id")

    @default_pool_id.setter
    def default_pool_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "default_pool_id", value)

    @_builtins.property
    @pulumi.getter(name="defaultTlsContainerRef")
    def default_tls_container_ref(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Reference to the default TLS container.
        """
        return pulumi.get(self, "default_tls_container_ref")

    @default_tls_container_ref.setter
    def default_tls_container_ref(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "default_tls_container_ref", value)

    @_builtins.property
    @pulumi.getter
    def description(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Description of the listener.
        """
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "description", value)

    @_builtins.property
    @pulumi.getter(name="insertHeaders")
    def insert_headers(self) -> Optional[pulumi.Input['CloudLoadbalancerListenerInsertHeadersArgs']]:
        """
        Headers to insert into requests:
        """
        return pulumi.get(self, "insert_headers")

    @insert_headers.setter
    def insert_headers(self, value: Optional[pulumi.Input['CloudLoadbalancerListenerInsertHeadersArgs']]):
        pulumi.set(self, "insert_headers", value)

    @_builtins.property
    @pulumi.getter(name="loadbalancerId")
    def loadbalancer_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        ID of the load balancer. **Changing this value recreates the resource.**
        """
        return pulumi.get(self, "loadbalancer_id")

    @loadbalancer_id.setter
    def loadbalancer_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "loadbalancer_id", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Name of the listener.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter
    def protocol(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Protocol of the listener (`HTTP`, `HTTPS`, `SCTP`, `TCP`, `TERMINATED_HTTPS`, `UDP`). **Changing this value recreates the resource.**
        """
        return pulumi.get(self, "protocol")

    @protocol.setter
    def protocol(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "protocol", value)

    @_builtins.property
    @pulumi.getter(name="protocolPort")
    def protocol_port(self) -> Optional[pulumi.Input[_builtins.int]]:
        """
        Port number the listener listens on. **Changing this value recreates the resource.**
        """
        return pulumi.get(self, "protocol_port")

    @protocol_port.setter
    def protocol_port(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "protocol_port", value)

    @_builtins.property
    @pulumi.getter(name="resourceStatus")
    def resource_status(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Listener readiness in the system (`CREATING`, `DELETING`, `ERROR`, `OUT_OF_SYNC`, `READY`, `UPDATING`).
        """
        return pulumi.get(self, "resource_status")

    @resource_status.setter
    def resource_status(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "resource_status", value)

    @_builtins.property
    @pulumi.getter(name="serviceName")
    def service_name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Service name of the resource representing the id of the cloud project. **Changing this value recreates the resource.**
        """
        return pulumi.get(self, "service_name")

    @service_name.setter
    def service_name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "service_name", value)

    @_builtins.property
    @pulumi.getter(name="sniContainerRefs")
    def sni_container_refs(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        List of SNI container references.
        """
        return pulumi.get(self, "sni_container_refs")

    @sni_container_refs.setter
    def sni_container_refs(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "sni_container_refs", value)

    @_builtins.property
    @pulumi.getter(name="timeoutClientData")
    def timeout_client_data(self) -> Optional[pulumi.Input[_builtins.int]]:
        """
        Timeout for client data in milliseconds. If omitted, the default assigned by the API is stored in the state.
        """
        return pulumi.get(self, "timeout_client_data")

    @timeout_client_data.setter
    def timeout_client_data(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "timeout_client_data", value)

    @_builtins.property
    @pulumi.getter(name="timeoutMemberConnect")
    def timeout_member_connect(self) -> Optional[pulumi.Input[_builtins.int]]:
        """
        Timeout for member connection in milliseconds. If omitted, the default assigned by the API is stored in the state.
        """
        return pulumi.get(self, "timeout_member_connect")

    @timeout_member_connect.setter
    def timeout_member_connect(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "timeout_member_connect", value)

    @_builtins.property
    @pulumi.getter(name="timeoutMemberData")
    def timeout_member_data(self) -> Optional[pulumi.Input[_builtins.int]]:
        """
        Timeout for member data in milliseconds. If omitted, the default assigned by the API is stored in the state.
        """
        return pulumi.get(self, "timeout_member_data")

    @timeout_member_data.setter
    def timeout_member_data(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "timeout_member_data", value)

    @_builtins.property
    @pulumi.getter(name="timeoutTcpInspect")
    def timeout_tcp_inspect(self) -> Optional[pulumi.Input[_builtins.int]]:
        """
        Timeout for TCP inspect in milliseconds. If omitted, the default assigned by the API is stored in the state.
        """
        return pulumi.get(self, "timeout_tcp_inspect")

    @timeout_tcp_inspect.setter
    def timeout_tcp_inspect(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "timeout_tcp_inspect", value)

    @_builtins.property
    @pulumi.getter(name="tlsVersions")
    def tls_versions(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        List of TLS versions allowed.
        """
        return pulumi.get(self, "tls_versions")

    @tls_versions.setter
    def tls_versions(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "tls_versions", value)

    @_builtins.property
    @pulumi.getter(name="updatedAt")
    def updated_at(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Last update date of the listener.
        """
        return pulumi.get(self, "updated_at")

    @updated_at.setter
    def updated_at(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "updated_at", value)


@pulumi.type_token("ovh:index/cloudLoadbalancerListener:CloudLoadbalancerListener")
class CloudLoadbalancerListener(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 allowed_cidrs: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 connection_limit: Optional[pulumi.Input[_builtins.int]] = None,
                 default_pool_id: Optional[pulumi.Input[_builtins.str]] = None,
                 default_tls_container_ref: Optional[pulumi.Input[_builtins.str]] = None,
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 insert_headers: Optional[pulumi.Input[Union['CloudLoadbalancerListenerInsertHeadersArgs', 'CloudLoadbalancerListenerInsertHeadersArgsDict']]] = None,
                 loadbalancer_id: Optional[pulumi.Input[_builtins.str]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 protocol: Optional[pulumi.Input[_builtins.str]] = None,
                 protocol_port: Optional[pulumi.Input[_builtins.int]] = None,
                 service_name: Optional[pulumi.Input[_builtins.str]] = None,
                 sni_container_refs: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 timeout_client_data: Optional[pulumi.Input[_builtins.int]] = None,
                 timeout_member_connect: Optional[pulumi.Input[_builtins.int]] = None,
                 timeout_member_data: Optional[pulumi.Input[_builtins.int]] = None,
                 timeout_tcp_inspect: Optional[pulumi.Input[_builtins.int]] = None,
                 tls_versions: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 __props__=None):
        """
        Creates a listener on a load balancer in a public cloud project.

        ## Example Usage

        ### Basic HTTP Listener

        ```python
        import pulumi
        import pulumi_ovh as ovh

        http = ovh.CloudLoadbalancerListener("http",
            service_name="xxxxxxxxxx",
            loadbalancer_id=lb["id"],
            name="http-listener",
            protocol="HTTP",
            protocol_port=80)
        ```

        ## Import

        A cloud load balancer listener can be imported using the `service_name`, `loadbalancer_id`, and `listener_id`, separated by `/`:

        terraform

        import {

          to = ovh_cloud_loadbalancer_listener.http

          id = "<service_name>/<loadbalancer_id>/<listener_id>"

        }

        bash

        ```sh
        $ pulumi import ovh:index/cloudLoadbalancerListener:CloudLoadbalancerListener http service_name/loadbalancer_id/listener_id
        ```

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] allowed_cidrs: List of CIDRs allowed to access the listener.
        :param pulumi.Input[_builtins.int] connection_limit: Maximum number of connections allowed. If omitted, the value assigned by the API is stored in the state.
        :param pulumi.Input[_builtins.str] default_pool_id: ID of the default pool for this listener (see `CloudLoadbalancerPool`). If omitted, the value assigned by the API is stored in the state.
        :param pulumi.Input[_builtins.str] default_tls_container_ref: Reference to the default TLS container.
        :param pulumi.Input[_builtins.str] description: Description of the listener.
        :param pulumi.Input[Union['CloudLoadbalancerListenerInsertHeadersArgs', 'CloudLoadbalancerListenerInsertHeadersArgsDict']] insert_headers: Headers to insert into requests:
        :param pulumi.Input[_builtins.str] loadbalancer_id: ID of the load balancer. **Changing this value recreates the resource.**
        :param pulumi.Input[_builtins.str] name: Name of the listener.
        :param pulumi.Input[_builtins.str] protocol: Protocol of the listener (`HTTP`, `HTTPS`, `SCTP`, `TCP`, `TERMINATED_HTTPS`, `UDP`). **Changing this value recreates the resource.**
        :param pulumi.Input[_builtins.int] protocol_port: Port number the listener listens on. **Changing this value recreates the resource.**
        :param pulumi.Input[_builtins.str] service_name: Service name of the resource representing the id of the cloud project. **Changing this value recreates the resource.**
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] sni_container_refs: List of SNI container references.
        :param pulumi.Input[_builtins.int] timeout_client_data: Timeout for client data in milliseconds. If omitted, the default assigned by the API is stored in the state.
        :param pulumi.Input[_builtins.int] timeout_member_connect: Timeout for member connection in milliseconds. If omitted, the default assigned by the API is stored in the state.
        :param pulumi.Input[_builtins.int] timeout_member_data: Timeout for member data in milliseconds. If omitted, the default assigned by the API is stored in the state.
        :param pulumi.Input[_builtins.int] timeout_tcp_inspect: Timeout for TCP inspect in milliseconds. If omitted, the default assigned by the API is stored in the state.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] tls_versions: List of TLS versions allowed.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: CloudLoadbalancerListenerArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Creates a listener on a load balancer in a public cloud project.

        ## Example Usage

        ### Basic HTTP Listener

        ```python
        import pulumi
        import pulumi_ovh as ovh

        http = ovh.CloudLoadbalancerListener("http",
            service_name="xxxxxxxxxx",
            loadbalancer_id=lb["id"],
            name="http-listener",
            protocol="HTTP",
            protocol_port=80)
        ```

        ## Import

        A cloud load balancer listener can be imported using the `service_name`, `loadbalancer_id`, and `listener_id`, separated by `/`:

        terraform

        import {

          to = ovh_cloud_loadbalancer_listener.http

          id = "<service_name>/<loadbalancer_id>/<listener_id>"

        }

        bash

        ```sh
        $ pulumi import ovh:index/cloudLoadbalancerListener:CloudLoadbalancerListener http service_name/loadbalancer_id/listener_id
        ```

        :param str resource_name: The name of the resource.
        :param CloudLoadbalancerListenerArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(CloudLoadbalancerListenerArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 allowed_cidrs: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 connection_limit: Optional[pulumi.Input[_builtins.int]] = None,
                 default_pool_id: Optional[pulumi.Input[_builtins.str]] = None,
                 default_tls_container_ref: Optional[pulumi.Input[_builtins.str]] = None,
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 insert_headers: Optional[pulumi.Input[Union['CloudLoadbalancerListenerInsertHeadersArgs', 'CloudLoadbalancerListenerInsertHeadersArgsDict']]] = None,
                 loadbalancer_id: Optional[pulumi.Input[_builtins.str]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 protocol: Optional[pulumi.Input[_builtins.str]] = None,
                 protocol_port: Optional[pulumi.Input[_builtins.int]] = None,
                 service_name: Optional[pulumi.Input[_builtins.str]] = None,
                 sni_container_refs: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 timeout_client_data: Optional[pulumi.Input[_builtins.int]] = None,
                 timeout_member_connect: Optional[pulumi.Input[_builtins.int]] = None,
                 timeout_member_data: Optional[pulumi.Input[_builtins.int]] = None,
                 timeout_tcp_inspect: Optional[pulumi.Input[_builtins.int]] = None,
                 tls_versions: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = CloudLoadbalancerListenerArgs.__new__(CloudLoadbalancerListenerArgs)

            __props__.__dict__["allowed_cidrs"] = allowed_cidrs
            __props__.__dict__["connection_limit"] = connection_limit
            __props__.__dict__["default_pool_id"] = default_pool_id
            __props__.__dict__["default_tls_container_ref"] = default_tls_container_ref
            __props__.__dict__["description"] = description
            __props__.__dict__["insert_headers"] = insert_headers
            if loadbalancer_id is None and not opts.urn:
                raise TypeError("Missing required property 'loadbalancer_id'")
            __props__.__dict__["loadbalancer_id"] = loadbalancer_id
            __props__.__dict__["name"] = name
            if protocol is None and not opts.urn:
                raise TypeError("Missing required property 'protocol'")
            __props__.__dict__["protocol"] = protocol
            if protocol_port is None and not opts.urn:
                raise TypeError("Missing required property 'protocol_port'")
            __props__.__dict__["protocol_port"] = protocol_port
            if service_name is None and not opts.urn:
                raise TypeError("Missing required property 'service_name'")
            __props__.__dict__["service_name"] = service_name
            __props__.__dict__["sni_container_refs"] = sni_container_refs
            __props__.__dict__["timeout_client_data"] = timeout_client_data
            __props__.__dict__["timeout_member_connect"] = timeout_member_connect
            __props__.__dict__["timeout_member_data"] = timeout_member_data
            __props__.__dict__["timeout_tcp_inspect"] = timeout_tcp_inspect
            __props__.__dict__["tls_versions"] = tls_versions
            __props__.__dict__["checksum"] = None
            __props__.__dict__["created_at"] = None
            __props__.__dict__["current_state"] = None
            __props__.__dict__["resource_status"] = None
            __props__.__dict__["updated_at"] = None
        super(CloudLoadbalancerListener, __self__).__init__(
            'ovh:index/cloudLoadbalancerListener:CloudLoadbalancerListener',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            allowed_cidrs: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
            checksum: Optional[pulumi.Input[_builtins.str]] = None,
            connection_limit: Optional[pulumi.Input[_builtins.int]] = None,
            created_at: Optional[pulumi.Input[_builtins.str]] = None,
            current_state: Optional[pulumi.Input[Union['CloudLoadbalancerListenerCurrentStateArgs', 'CloudLoadbalancerListenerCurrentStateArgsDict']]] = None,
            default_pool_id: Optional[pulumi.Input[_builtins.str]] = None,
            default_tls_container_ref: Optional[pulumi.Input[_builtins.str]] = None,
            description: Optional[pulumi.Input[_builtins.str]] = None,
            insert_headers: Optional[pulumi.Input[Union['CloudLoadbalancerListenerInsertHeadersArgs', 'CloudLoadbalancerListenerInsertHeadersArgsDict']]] = None,
            loadbalancer_id: Optional[pulumi.Input[_builtins.str]] = None,
            name: Optional[pulumi.Input[_builtins.str]] = None,
            protocol: Optional[pulumi.Input[_builtins.str]] = None,
            protocol_port: Optional[pulumi.Input[_builtins.int]] = None,
            resource_status: Optional[pulumi.Input[_builtins.str]] = None,
            service_name: Optional[pulumi.Input[_builtins.str]] = None,
            sni_container_refs: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
            timeout_client_data: Optional[pulumi.Input[_builtins.int]] = None,
            timeout_member_connect: Optional[pulumi.Input[_builtins.int]] = None,
            timeout_member_data: Optional[pulumi.Input[_builtins.int]] = None,
            timeout_tcp_inspect: Optional[pulumi.Input[_builtins.int]] = None,
            tls_versions: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
            updated_at: Optional[pulumi.Input[_builtins.str]] = None) -> 'CloudLoadbalancerListener':
        """
        Get an existing CloudLoadbalancerListener resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] allowed_cidrs: List of CIDRs allowed to access the listener.
        :param pulumi.Input[_builtins.str] checksum: Computed hash representing the current target specification value.
        :param pulumi.Input[_builtins.int] connection_limit: Maximum number of connections allowed. If omitted, the value assigned by the API is stored in the state.
        :param pulumi.Input[_builtins.str] created_at: Creation date of the listener.
        :param pulumi.Input[Union['CloudLoadbalancerListenerCurrentStateArgs', 'CloudLoadbalancerListenerCurrentStateArgsDict']] current_state: Current state of the listener:
        :param pulumi.Input[_builtins.str] default_pool_id: ID of the default pool for this listener (see `CloudLoadbalancerPool`). If omitted, the value assigned by the API is stored in the state.
        :param pulumi.Input[_builtins.str] default_tls_container_ref: Reference to the default TLS container.
        :param pulumi.Input[_builtins.str] description: Description of the listener.
        :param pulumi.Input[Union['CloudLoadbalancerListenerInsertHeadersArgs', 'CloudLoadbalancerListenerInsertHeadersArgsDict']] insert_headers: Headers to insert into requests:
        :param pulumi.Input[_builtins.str] loadbalancer_id: ID of the load balancer. **Changing this value recreates the resource.**
        :param pulumi.Input[_builtins.str] name: Name of the listener.
        :param pulumi.Input[_builtins.str] protocol: Protocol of the listener (`HTTP`, `HTTPS`, `SCTP`, `TCP`, `TERMINATED_HTTPS`, `UDP`). **Changing this value recreates the resource.**
        :param pulumi.Input[_builtins.int] protocol_port: Port number the listener listens on. **Changing this value recreates the resource.**
        :param pulumi.Input[_builtins.str] resource_status: Listener readiness in the system (`CREATING`, `DELETING`, `ERROR`, `OUT_OF_SYNC`, `READY`, `UPDATING`).
        :param pulumi.Input[_builtins.str] service_name: Service name of the resource representing the id of the cloud project. **Changing this value recreates the resource.**
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] sni_container_refs: List of SNI container references.
        :param pulumi.Input[_builtins.int] timeout_client_data: Timeout for client data in milliseconds. If omitted, the default assigned by the API is stored in the state.
        :param pulumi.Input[_builtins.int] timeout_member_connect: Timeout for member connection in milliseconds. If omitted, the default assigned by the API is stored in the state.
        :param pulumi.Input[_builtins.int] timeout_member_data: Timeout for member data in milliseconds. If omitted, the default assigned by the API is stored in the state.
        :param pulumi.Input[_builtins.int] timeout_tcp_inspect: Timeout for TCP inspect in milliseconds. If omitted, the default assigned by the API is stored in the state.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] tls_versions: List of TLS versions allowed.
        :param pulumi.Input[_builtins.str] updated_at: Last update date of the listener.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _CloudLoadbalancerListenerState.__new__(_CloudLoadbalancerListenerState)

        __props__.__dict__["allowed_cidrs"] = allowed_cidrs
        __props__.__dict__["checksum"] = checksum
        __props__.__dict__["connection_limit"] = connection_limit
        __props__.__dict__["created_at"] = created_at
        __props__.__dict__["current_state"] = current_state
        __props__.__dict__["default_pool_id"] = default_pool_id
        __props__.__dict__["default_tls_container_ref"] = default_tls_container_ref
        __props__.__dict__["description"] = description
        __props__.__dict__["insert_headers"] = insert_headers
        __props__.__dict__["loadbalancer_id"] = loadbalancer_id
        __props__.__dict__["name"] = name
        __props__.__dict__["protocol"] = protocol
        __props__.__dict__["protocol_port"] = protocol_port
        __props__.__dict__["resource_status"] = resource_status
        __props__.__dict__["service_name"] = service_name
        __props__.__dict__["sni_container_refs"] = sni_container_refs
        __props__.__dict__["timeout_client_data"] = timeout_client_data
        __props__.__dict__["timeout_member_connect"] = timeout_member_connect
        __props__.__dict__["timeout_member_data"] = timeout_member_data
        __props__.__dict__["timeout_tcp_inspect"] = timeout_tcp_inspect
        __props__.__dict__["tls_versions"] = tls_versions
        __props__.__dict__["updated_at"] = updated_at
        return CloudLoadbalancerListener(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="allowedCidrs")
    def allowed_cidrs(self) -> pulumi.Output[Optional[Sequence[_builtins.str]]]:
        """
        List of CIDRs allowed to access the listener.
        """
        return pulumi.get(self, "allowed_cidrs")

    @_builtins.property
    @pulumi.getter
    def checksum(self) -> pulumi.Output[_builtins.str]:
        """
        Computed hash representing the current target specification value.
        """
        return pulumi.get(self, "checksum")

    @_builtins.property
    @pulumi.getter(name="connectionLimit")
    def connection_limit(self) -> pulumi.Output[_builtins.int]:
        """
        Maximum number of connections allowed. If omitted, the value assigned by the API is stored in the state.
        """
        return pulumi.get(self, "connection_limit")

    @_builtins.property
    @pulumi.getter(name="createdAt")
    def created_at(self) -> pulumi.Output[_builtins.str]:
        """
        Creation date of the listener.
        """
        return pulumi.get(self, "created_at")

    @_builtins.property
    @pulumi.getter(name="currentState")
    def current_state(self) -> pulumi.Output['outputs.CloudLoadbalancerListenerCurrentState']:
        """
        Current state of the listener:
        """
        return pulumi.get(self, "current_state")

    @_builtins.property
    @pulumi.getter(name="defaultPoolId")
    def default_pool_id(self) -> pulumi.Output[_builtins.str]:
        """
        ID of the default pool for this listener (see `CloudLoadbalancerPool`). If omitted, the value assigned by the API is stored in the state.
        """
        return pulumi.get(self, "default_pool_id")

    @_builtins.property
    @pulumi.getter(name="defaultTlsContainerRef")
    def default_tls_container_ref(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Reference to the default TLS container.
        """
        return pulumi.get(self, "default_tls_container_ref")

    @_builtins.property
    @pulumi.getter
    def description(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Description of the listener.
        """
        return pulumi.get(self, "description")

    @_builtins.property
    @pulumi.getter(name="insertHeaders")
    def insert_headers(self) -> pulumi.Output[Optional['outputs.CloudLoadbalancerListenerInsertHeaders']]:
        """
        Headers to insert into requests:
        """
        return pulumi.get(self, "insert_headers")

    @_builtins.property
    @pulumi.getter(name="loadbalancerId")
    def loadbalancer_id(self) -> pulumi.Output[_builtins.str]:
        """
        ID of the load balancer. **Changing this value recreates the resource.**
        """
        return pulumi.get(self, "loadbalancer_id")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        """
        Name of the listener.
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter
    def protocol(self) -> pulumi.Output[_builtins.str]:
        """
        Protocol of the listener (`HTTP`, `HTTPS`, `SCTP`, `TCP`, `TERMINATED_HTTPS`, `UDP`). **Changing this value recreates the resource.**
        """
        return pulumi.get(self, "protocol")

    @_builtins.property
    @pulumi.getter(name="protocolPort")
    def protocol_port(self) -> pulumi.Output[_builtins.int]:
        """
        Port number the listener listens on. **Changing this value recreates the resource.**
        """
        return pulumi.get(self, "protocol_port")

    @_builtins.property
    @pulumi.getter(name="resourceStatus")
    def resource_status(self) -> pulumi.Output[_builtins.str]:
        """
        Listener readiness in the system (`CREATING`, `DELETING`, `ERROR`, `OUT_OF_SYNC`, `READY`, `UPDATING`).
        """
        return pulumi.get(self, "resource_status")

    @_builtins.property
    @pulumi.getter(name="serviceName")
    def service_name(self) -> pulumi.Output[_builtins.str]:
        """
        Service name of the resource representing the id of the cloud project. **Changing this value recreates the resource.**
        """
        return pulumi.get(self, "service_name")

    @_builtins.property
    @pulumi.getter(name="sniContainerRefs")
    def sni_container_refs(self) -> pulumi.Output[Optional[Sequence[_builtins.str]]]:
        """
        List of SNI container references.
        """
        return pulumi.get(self, "sni_container_refs")

    @_builtins.property
    @pulumi.getter(name="timeoutClientData")
    def timeout_client_data(self) -> pulumi.Output[_builtins.int]:
        """
        Timeout for client data in milliseconds. If omitted, the default assigned by the API is stored in the state.
        """
        return pulumi.get(self, "timeout_client_data")

    @_builtins.property
    @pulumi.getter(name="timeoutMemberConnect")
    def timeout_member_connect(self) -> pulumi.Output[_builtins.int]:
        """
        Timeout for member connection in milliseconds. If omitted, the default assigned by the API is stored in the state.
        """
        return pulumi.get(self, "timeout_member_connect")

    @_builtins.property
    @pulumi.getter(name="timeoutMemberData")
    def timeout_member_data(self) -> pulumi.Output[_builtins.int]:
        """
        Timeout for member data in milliseconds. If omitted, the default assigned by the API is stored in the state.
        """
        return pulumi.get(self, "timeout_member_data")

    @_builtins.property
    @pulumi.getter(name="timeoutTcpInspect")
    def timeout_tcp_inspect(self) -> pulumi.Output[_builtins.int]:
        """
        Timeout for TCP inspect in milliseconds. If omitted, the default assigned by the API is stored in the state.
        """
        return pulumi.get(self, "timeout_tcp_inspect")

    @_builtins.property
    @pulumi.getter(name="tlsVersions")
    def tls_versions(self) -> pulumi.Output[Optional[Sequence[_builtins.str]]]:
        """
        List of TLS versions allowed.
        """
        return pulumi.get(self, "tls_versions")

    @_builtins.property
    @pulumi.getter(name="updatedAt")
    def updated_at(self) -> pulumi.Output[_builtins.str]:
        """
        Last update date of the listener.
        """
        return pulumi.get(self, "updated_at")

