// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.ovh.ovh.Dedicated.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.Double;
import java.lang.String;
import java.util.List;
import java.util.Objects;

@CustomType
public final class GetCephResult {
    /**
     * @return URN of the CEPH instance
     * 
     */
    private String CephURN;
    /**
     * @return list of CEPH monitors IPs
     * 
     */
    private List<String> cephMons;
    /**
     * @return CEPH cluster version
     * 
     */
    private String cephVersion;
    /**
     * @return CRUSH algorithm settings. Possible values
     * * OPTIMAL
     * * DEFAULT
     * * LEGACY
     * * BOBTAIL
     * * ARGONAUT
     * * FIREFLY
     * * HAMMER
     * * JEWEL
     * 
     */
    private String crushTunables;
    /**
     * @return The provider-assigned unique ID for this managed resource.
     * 
     */
    private String id;
    /**
     * @return CEPH cluster label
     * 
     */
    private String label;
    /**
     * @return cluster region
     * 
     */
    private String region;
    private String serviceName;
    /**
     * @return Cluster size in TB
     * 
     */
    private Double size;
    /**
     * @return the state of the cluster
     * 
     */
    private String state;
    /**
     * @return the status of the service
     * 
     */
    private String status;

    private GetCephResult() {}
    /**
     * @return URN of the CEPH instance
     * 
     */
    public String CephURN() {
        return this.CephURN;
    }
    /**
     * @return list of CEPH monitors IPs
     * 
     */
    public List<String> cephMons() {
        return this.cephMons;
    }
    /**
     * @return CEPH cluster version
     * 
     */
    public String cephVersion() {
        return this.cephVersion;
    }
    /**
     * @return CRUSH algorithm settings. Possible values
     * * OPTIMAL
     * * DEFAULT
     * * LEGACY
     * * BOBTAIL
     * * ARGONAUT
     * * FIREFLY
     * * HAMMER
     * * JEWEL
     * 
     */
    public String crushTunables() {
        return this.crushTunables;
    }
    /**
     * @return The provider-assigned unique ID for this managed resource.
     * 
     */
    public String id() {
        return this.id;
    }
    /**
     * @return CEPH cluster label
     * 
     */
    public String label() {
        return this.label;
    }
    /**
     * @return cluster region
     * 
     */
    public String region() {
        return this.region;
    }
    public String serviceName() {
        return this.serviceName;
    }
    /**
     * @return Cluster size in TB
     * 
     */
    public Double size() {
        return this.size;
    }
    /**
     * @return the state of the cluster
     * 
     */
    public String state() {
        return this.state;
    }
    /**
     * @return the status of the service
     * 
     */
    public String status() {
        return this.status;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetCephResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String CephURN;
        private List<String> cephMons;
        private String cephVersion;
        private String crushTunables;
        private String id;
        private String label;
        private String region;
        private String serviceName;
        private Double size;
        private String state;
        private String status;
        public Builder() {}
        public Builder(GetCephResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.CephURN = defaults.CephURN;
    	      this.cephMons = defaults.cephMons;
    	      this.cephVersion = defaults.cephVersion;
    	      this.crushTunables = defaults.crushTunables;
    	      this.id = defaults.id;
    	      this.label = defaults.label;
    	      this.region = defaults.region;
    	      this.serviceName = defaults.serviceName;
    	      this.size = defaults.size;
    	      this.state = defaults.state;
    	      this.status = defaults.status;
        }

        @CustomType.Setter
        public Builder CephURN(String CephURN) {
            this.CephURN = Objects.requireNonNull(CephURN);
            return this;
        }
        @CustomType.Setter
        public Builder cephMons(List<String> cephMons) {
            this.cephMons = Objects.requireNonNull(cephMons);
            return this;
        }
        public Builder cephMons(String... cephMons) {
            return cephMons(List.of(cephMons));
        }
        @CustomType.Setter
        public Builder cephVersion(String cephVersion) {
            this.cephVersion = Objects.requireNonNull(cephVersion);
            return this;
        }
        @CustomType.Setter
        public Builder crushTunables(String crushTunables) {
            this.crushTunables = Objects.requireNonNull(crushTunables);
            return this;
        }
        @CustomType.Setter
        public Builder id(String id) {
            this.id = Objects.requireNonNull(id);
            return this;
        }
        @CustomType.Setter
        public Builder label(String label) {
            this.label = Objects.requireNonNull(label);
            return this;
        }
        @CustomType.Setter
        public Builder region(String region) {
            this.region = Objects.requireNonNull(region);
            return this;
        }
        @CustomType.Setter
        public Builder serviceName(String serviceName) {
            this.serviceName = Objects.requireNonNull(serviceName);
            return this;
        }
        @CustomType.Setter
        public Builder size(Double size) {
            this.size = Objects.requireNonNull(size);
            return this;
        }
        @CustomType.Setter
        public Builder state(String state) {
            this.state = Objects.requireNonNull(state);
            return this;
        }
        @CustomType.Setter
        public Builder status(String status) {
            this.status = Objects.requireNonNull(status);
            return this;
        }
        public GetCephResult build() {
            final var o = new GetCephResult();
            o.CephURN = CephURN;
            o.cephMons = cephMons;
            o.cephVersion = cephVersion;
            o.crushTunables = crushTunables;
            o.id = id;
            o.label = label;
            o.region = region;
            o.serviceName = serviceName;
            o.size = size;
            o.state = state;
            o.status = status;
            return o;
        }
    }
}
