// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Creates a block storage volume backup in a public cloud project.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as ovh from "@ovhcloud/pulumi-ovh";
 *
 * const backup = new ovh.CloudStorageBlockVolumeBackup("backup", {
 *     serviceName: "xxxxxxxxx",
 *     name: "my-backup",
 *     description: "Daily backup",
 *     region: "GRA9",
 *     volumeId: volume.id,
 * });
 * ```
 *
 * ## Import
 *
 * A block storage volume backup can be imported using the `service_name` and `id` separated by a `/`:
 *
 * bash
 *
 * ```sh
 * $ pulumi import ovh:index/cloudStorageBlockVolumeBackup:CloudStorageBlockVolumeBackup backup service_name/backup_id
 * ```
 */
export class CloudStorageBlockVolumeBackup extends pulumi.CustomResource {
    /**
     * Get an existing CloudStorageBlockVolumeBackup resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: CloudStorageBlockVolumeBackupState, opts?: pulumi.CustomResourceOptions): CloudStorageBlockVolumeBackup {
        return new CloudStorageBlockVolumeBackup(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'ovh:index/cloudStorageBlockVolumeBackup:CloudStorageBlockVolumeBackup';

    /**
     * Returns true if the given object is an instance of CloudStorageBlockVolumeBackup.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is CloudStorageBlockVolumeBackup {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === CloudStorageBlockVolumeBackup.__pulumiType;
    }

    /**
     * Computed hash representing the current target specification value.
     */
    public /*out*/ readonly checksum!: pulumi.Output<string>;
    /**
     * Creation date of the backup.
     */
    public /*out*/ readonly createdAt!: pulumi.Output<string>;
    /**
     * Current state of the backup:
     */
    public /*out*/ readonly currentState!: pulumi.Output<outputs.CloudStorageBlockVolumeBackupCurrentState>;
    /**
     * A description for the backup.
     */
    public readonly description!: pulumi.Output<string>;
    /**
     * The name of the backup.
     */
    public readonly name!: pulumi.Output<string>;
    /**
     * The region where the backup will be created. Changing this value recreates the resource.
     */
    public readonly region!: pulumi.Output<string>;
    /**
     * Backup readiness in the system (`CREATING`, `DELETING`, `ERROR`, `OUT_OF_SYNC`, `READY`, `UPDATING`).
     */
    public /*out*/ readonly resourceStatus!: pulumi.Output<string>;
    /**
     * The id of the public cloud project. Changing this value recreates the resource.
     */
    public readonly serviceName!: pulumi.Output<string>;
    /**
     * Last update date of the backup.
     */
    public /*out*/ readonly updatedAt!: pulumi.Output<string>;
    /**
     * The ID of the volume to back up. Changing this value recreates the resource.
     */
    public readonly volumeId!: pulumi.Output<string>;

    /**
     * Create a CloudStorageBlockVolumeBackup resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: CloudStorageBlockVolumeBackupArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: CloudStorageBlockVolumeBackupArgs | CloudStorageBlockVolumeBackupState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as CloudStorageBlockVolumeBackupState | undefined;
            resourceInputs["checksum"] = state ? state.checksum : undefined;
            resourceInputs["createdAt"] = state ? state.createdAt : undefined;
            resourceInputs["currentState"] = state ? state.currentState : undefined;
            resourceInputs["description"] = state ? state.description : undefined;
            resourceInputs["name"] = state ? state.name : undefined;
            resourceInputs["region"] = state ? state.region : undefined;
            resourceInputs["resourceStatus"] = state ? state.resourceStatus : undefined;
            resourceInputs["serviceName"] = state ? state.serviceName : undefined;
            resourceInputs["updatedAt"] = state ? state.updatedAt : undefined;
            resourceInputs["volumeId"] = state ? state.volumeId : undefined;
        } else {
            const args = argsOrState as CloudStorageBlockVolumeBackupArgs | undefined;
            if ((!args || args.region === undefined) && !opts.urn) {
                throw new Error("Missing required property 'region'");
            }
            if ((!args || args.serviceName === undefined) && !opts.urn) {
                throw new Error("Missing required property 'serviceName'");
            }
            if ((!args || args.volumeId === undefined) && !opts.urn) {
                throw new Error("Missing required property 'volumeId'");
            }
            resourceInputs["description"] = args ? args.description : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["region"] = args ? args.region : undefined;
            resourceInputs["serviceName"] = args ? args.serviceName : undefined;
            resourceInputs["volumeId"] = args ? args.volumeId : undefined;
            resourceInputs["checksum"] = undefined /*out*/;
            resourceInputs["createdAt"] = undefined /*out*/;
            resourceInputs["currentState"] = undefined /*out*/;
            resourceInputs["resourceStatus"] = undefined /*out*/;
            resourceInputs["updatedAt"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(CloudStorageBlockVolumeBackup.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering CloudStorageBlockVolumeBackup resources.
 */
export interface CloudStorageBlockVolumeBackupState {
    /**
     * Computed hash representing the current target specification value.
     */
    checksum?: pulumi.Input<string>;
    /**
     * Creation date of the backup.
     */
    createdAt?: pulumi.Input<string>;
    /**
     * Current state of the backup:
     */
    currentState?: pulumi.Input<inputs.CloudStorageBlockVolumeBackupCurrentState>;
    /**
     * A description for the backup.
     */
    description?: pulumi.Input<string>;
    /**
     * The name of the backup.
     */
    name?: pulumi.Input<string>;
    /**
     * The region where the backup will be created. Changing this value recreates the resource.
     */
    region?: pulumi.Input<string>;
    /**
     * Backup readiness in the system (`CREATING`, `DELETING`, `ERROR`, `OUT_OF_SYNC`, `READY`, `UPDATING`).
     */
    resourceStatus?: pulumi.Input<string>;
    /**
     * The id of the public cloud project. Changing this value recreates the resource.
     */
    serviceName?: pulumi.Input<string>;
    /**
     * Last update date of the backup.
     */
    updatedAt?: pulumi.Input<string>;
    /**
     * The ID of the volume to back up. Changing this value recreates the resource.
     */
    volumeId?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a CloudStorageBlockVolumeBackup resource.
 */
export interface CloudStorageBlockVolumeBackupArgs {
    /**
     * A description for the backup.
     */
    description?: pulumi.Input<string>;
    /**
     * The name of the backup.
     */
    name?: pulumi.Input<string>;
    /**
     * The region where the backup will be created. Changing this value recreates the resource.
     */
    region: pulumi.Input<string>;
    /**
     * The id of the public cloud project. Changing this value recreates the resource.
     */
    serviceName: pulumi.Input<string>;
    /**
     * The ID of the volume to back up. Changing this value recreates the resource.
     */
    volumeId: pulumi.Input<string>;
}
